/*
Manager system API

This application demonstrates the usage of Manager system API.

API version: 6.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
)

// NACPortProfilesAPIService NACPortProfilesAPI service
type NACPortProfilesAPIService service

type ApiNacportprofilesDeleteRequest struct {
	ctx                context.Context
	ApiService         *NACPortProfilesAPIService
	nacPortProfileName *[]string
	changesetName      *string
}

func (r ApiNacportprofilesDeleteRequest) NacPortProfileName(nacPortProfileName []string) ApiNacportprofilesDeleteRequest {
	r.nacPortProfileName = &nacPortProfileName
	return r
}

func (r ApiNacportprofilesDeleteRequest) ChangesetName(changesetName string) ApiNacportprofilesDeleteRequest {
	r.changesetName = &changesetName
	return r
}

func (r ApiNacportprofilesDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.NacportprofilesDeleteExecute(r)
}

/*
NacportprofilesDelete Delete NAC Port Profile

Deletes an existing NAC Port Profile from the system if changeset_name is empty, from a changeset if its name is provided.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiNacportprofilesDeleteRequest
*/
func (a *NACPortProfilesAPIService) NacportprofilesDelete(ctx context.Context) ApiNacportprofilesDeleteRequest {
	return ApiNacportprofilesDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *NACPortProfilesAPIService) NacportprofilesDeleteExecute(r ApiNacportprofilesDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodDelete
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NACPortProfilesAPIService.NacportprofilesDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/nacportprofiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.nacPortProfileName == nil {
		return nil, reportError("nacPortProfileName is required and must be specified")
	}

	{
		t := *r.nacPortProfileName
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "nac_port_profile_name", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "nac_port_profile_name", t, "form", "multi")
		}
	}
	if r.changesetName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "changeset_name", r.changesetName, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiNacportprofilesGetRequest struct {
	ctx                context.Context
	ApiService         *NACPortProfilesAPIService
	nacPortProfileName *string
	includeData        *bool
	changesetName      *string
}

func (r ApiNacportprofilesGetRequest) NacPortProfileName(nacPortProfileName string) ApiNacportprofilesGetRequest {
	r.nacPortProfileName = &nacPortProfileName
	return r
}

func (r ApiNacportprofilesGetRequest) IncludeData(includeData bool) ApiNacportprofilesGetRequest {
	r.includeData = &includeData
	return r
}

func (r ApiNacportprofilesGetRequest) ChangesetName(changesetName string) ApiNacportprofilesGetRequest {
	r.changesetName = &changesetName
	return r
}

func (r ApiNacportprofilesGetRequest) Execute() (*http.Response, error) {
	return r.ApiService.NacportprofilesGetExecute(r)
}

/*
NacportprofilesGet Get all NAC Port Profiles

Retrieves all NAC Port Profiles from the system.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiNacportprofilesGetRequest
*/
func (a *NACPortProfilesAPIService) NacportprofilesGet(ctx context.Context) ApiNacportprofilesGetRequest {
	return ApiNacportprofilesGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *NACPortProfilesAPIService) NacportprofilesGetExecute(r ApiNacportprofilesGetRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodGet
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NACPortProfilesAPIService.NacportprofilesGet")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/nacportprofiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.nacPortProfileName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "nac_port_profile_name", r.nacPortProfileName, "form", "")
	}
	if r.includeData != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "include_data", r.includeData, "form", "")
	}
	if r.changesetName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "changeset_name", r.changesetName, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiNacportprofilesPatchRequest struct {
	ctx                       context.Context
	ApiService                *NACPortProfilesAPIService
	changesetName             *string
	nacportprofilesPutRequest *NacportprofilesPutRequest
}

func (r ApiNacportprofilesPatchRequest) ChangesetName(changesetName string) ApiNacportprofilesPatchRequest {
	r.changesetName = &changesetName
	return r
}

func (r ApiNacportprofilesPatchRequest) NacportprofilesPutRequest(nacportprofilesPutRequest NacportprofilesPutRequest) ApiNacportprofilesPatchRequest {
	r.nacportprofilesPutRequest = &nacportprofilesPutRequest
	return r
}

func (r ApiNacportprofilesPatchRequest) Execute() (*http.Response, error) {
	return r.ApiService.NacportprofilesPatchExecute(r)
}

/*
NacportprofilesPatch Update NAC Port Profile

Update NAC Port Profile into the system if changeset_name is empty, into a changeset if its name is provided.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiNacportprofilesPatchRequest
*/
func (a *NACPortProfilesAPIService) NacportprofilesPatch(ctx context.Context) ApiNacportprofilesPatchRequest {
	return ApiNacportprofilesPatchRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *NACPortProfilesAPIService) NacportprofilesPatchExecute(r ApiNacportprofilesPatchRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPatch
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NACPortProfilesAPIService.NacportprofilesPatch")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/nacportprofiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.changesetName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "changeset_name", r.changesetName, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nacportprofilesPutRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiNacportprofilesPutRequest struct {
	ctx                       context.Context
	ApiService                *NACPortProfilesAPIService
	changesetName             *string
	nacportprofilesPutRequest *NacportprofilesPutRequest
}

func (r ApiNacportprofilesPutRequest) ChangesetName(changesetName string) ApiNacportprofilesPutRequest {
	r.changesetName = &changesetName
	return r
}

func (r ApiNacportprofilesPutRequest) NacportprofilesPutRequest(nacportprofilesPutRequest NacportprofilesPutRequest) ApiNacportprofilesPutRequest {
	r.nacportprofilesPutRequest = &nacportprofilesPutRequest
	return r
}

func (r ApiNacportprofilesPutRequest) Execute() (*http.Response, error) {
	return r.ApiService.NacportprofilesPutExecute(r)
}

/*
NacportprofilesPut Create NAC Port Profile

Create NAC Port Profile into the system if changeset_name is empty, into a changeset if its name is provided.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiNacportprofilesPutRequest
*/
func (a *NACPortProfilesAPIService) NacportprofilesPut(ctx context.Context) ApiNacportprofilesPutRequest {
	return ApiNacportprofilesPutRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
func (a *NACPortProfilesAPIService) NacportprofilesPutExecute(r ApiNacportprofilesPutRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod = http.MethodPut
		localVarPostBody   interface{}
		formFiles          []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "NACPortProfilesAPIService.NacportprofilesPut")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/nacportprofiles"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.changesetName != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "changeset_name", r.changesetName, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.nacportprofilesPutRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}
