/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestPacketQueuePacketQueueNameObjectProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestPacketQueuePacketQueueNameObjectProperties{}

// ConfigPutRequestPacketQueuePacketQueueNameObjectProperties struct for ConfigPutRequestPacketQueuePacketQueueNameObjectProperties
type ConfigPutRequestPacketQueuePacketQueueNameObjectProperties struct {
	// Default object.
	Isdefault *bool `json:"isdefault,omitempty"`
	// Group
	Group *string `json:"group,omitempty"`
}

// NewConfigPutRequestPacketQueuePacketQueueNameObjectProperties instantiates a new ConfigPutRequestPacketQueuePacketQueueNameObjectProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestPacketQueuePacketQueueNameObjectProperties() *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties {
	this := ConfigPutRequestPacketQueuePacketQueueNameObjectProperties{}
	var isdefault bool = false
	this.Isdefault = &isdefault
	var group string = ""
	this.Group = &group
	return &this
}

// NewConfigPutRequestPacketQueuePacketQueueNameObjectPropertiesWithDefaults instantiates a new ConfigPutRequestPacketQueuePacketQueueNameObjectProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestPacketQueuePacketQueueNameObjectPropertiesWithDefaults() *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties {
	this := ConfigPutRequestPacketQueuePacketQueueNameObjectProperties{}
	var isdefault bool = false
	this.Isdefault = &isdefault
	var group string = ""
	this.Group = &group
	return &this
}

// GetIsdefault returns the Isdefault field value if set, zero value otherwise.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) GetIsdefault() bool {
	if o == nil || IsNil(o.Isdefault) {
		var ret bool
		return ret
	}
	return *o.Isdefault
}

// GetIsdefaultOk returns a tuple with the Isdefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) GetIsdefaultOk() (*bool, bool) {
	if o == nil || IsNil(o.Isdefault) {
		return nil, false
	}
	return o.Isdefault, true
}

// HasIsdefault returns a boolean if a field has been set.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) HasIsdefault() bool {
	if o != nil && !IsNil(o.Isdefault) {
		return true
	}

	return false
}

// SetIsdefault gets a reference to the given bool and assigns it to the Isdefault field.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) SetIsdefault(v bool) {
	o.Isdefault = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) SetGroup(v string) {
	o.Group = &v
}

func (o ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Isdefault) {
		toSerialize["isdefault"] = o.Isdefault
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties struct {
	value *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties
	isSet bool
}

func (v NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) Get() *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties {
	return v.value
}

func (v *NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) Set(val *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties(val *ConfigPutRequestPacketQueuePacketQueueNameObjectProperties) *NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties {
	return &NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties{value: val, isSet: true}
}

func (v NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestPacketQueuePacketQueueNameObjectProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


