/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestIpv6PrefixListIpv6PrefixListName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestIpv6PrefixListIpv6PrefixListName{}

// ConfigPutRequestIpv6PrefixListIpv6PrefixListName struct for ConfigPutRequestIpv6PrefixListIpv6PrefixListName
type ConfigPutRequestIpv6PrefixListIpv6PrefixListName struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	Lists []ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner `json:"lists,omitempty"`
	ObjectProperties *ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties `json:"object_properties,omitempty"`
}

// NewConfigPutRequestIpv6PrefixListIpv6PrefixListName instantiates a new ConfigPutRequestIpv6PrefixListIpv6PrefixListName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestIpv6PrefixListIpv6PrefixListName() *ConfigPutRequestIpv6PrefixListIpv6PrefixListName {
	this := ConfigPutRequestIpv6PrefixListIpv6PrefixListName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// NewConfigPutRequestIpv6PrefixListIpv6PrefixListNameWithDefaults instantiates a new ConfigPutRequestIpv6PrefixListIpv6PrefixListName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestIpv6PrefixListIpv6PrefixListNameWithDefaults() *ConfigPutRequestIpv6PrefixListIpv6PrefixListName {
	this := ConfigPutRequestIpv6PrefixListIpv6PrefixListName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) SetEnable(v bool) {
	o.Enable = &v
}

// GetLists returns the Lists field value if set, zero value otherwise.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetLists() []ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner {
	if o == nil || IsNil(o.Lists) {
		var ret []ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner
		return ret
	}
	return o.Lists
}

// GetListsOk returns a tuple with the Lists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetListsOk() ([]ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner, bool) {
	if o == nil || IsNil(o.Lists) {
		return nil, false
	}
	return o.Lists, true
}

// HasLists returns a boolean if a field has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) HasLists() bool {
	if o != nil && !IsNil(o.Lists) {
		return true
	}

	return false
}

// SetLists gets a reference to the given []ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner and assigns it to the Lists field.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) SetLists(v []ConfigPutRequestIpv6PrefixListIpv6PrefixListNameListsInner) {
	o.Lists = v
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetObjectProperties() ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) GetObjectPropertiesOk() (*ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties and assigns it to the ObjectProperties field.
func (o *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) SetObjectProperties(v ConfigPutRequestIpv4PrefixListIpv4PrefixListNameObjectProperties) {
	o.ObjectProperties = &v
}

func (o ConfigPutRequestIpv6PrefixListIpv6PrefixListName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestIpv6PrefixListIpv6PrefixListName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Lists) {
		toSerialize["lists"] = o.Lists
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName struct {
	value *ConfigPutRequestIpv6PrefixListIpv6PrefixListName
	isSet bool
}

func (v NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) Get() *ConfigPutRequestIpv6PrefixListIpv6PrefixListName {
	return v.value
}

func (v *NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) Set(val *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestIpv6PrefixListIpv6PrefixListName(val *ConfigPutRequestIpv6PrefixListIpv6PrefixListName) *NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName {
	return &NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName{value: val, isSet: true}
}

func (v NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestIpv6PrefixListIpv6PrefixListName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


