/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AspathaccesslistsPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AspathaccesslistsPutRequest{}

// AspathaccesslistsPutRequest struct for AspathaccesslistsPutRequest
type AspathaccesslistsPutRequest struct {
	AsPathAccessList *map[string]AspathaccesslistsPutRequestAsPathAccessListValue `json:"as_path_access_list,omitempty"`
}

// NewAspathaccesslistsPutRequest instantiates a new AspathaccesslistsPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAspathaccesslistsPutRequest() *AspathaccesslistsPutRequest {
	this := AspathaccesslistsPutRequest{}
	return &this
}

// NewAspathaccesslistsPutRequestWithDefaults instantiates a new AspathaccesslistsPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAspathaccesslistsPutRequestWithDefaults() *AspathaccesslistsPutRequest {
	this := AspathaccesslistsPutRequest{}
	return &this
}

// GetAsPathAccessList returns the AsPathAccessList field value if set, zero value otherwise.
func (o *AspathaccesslistsPutRequest) GetAsPathAccessList() map[string]AspathaccesslistsPutRequestAsPathAccessListValue {
	if o == nil || IsNil(o.AsPathAccessList) {
		var ret map[string]AspathaccesslistsPutRequestAsPathAccessListValue
		return ret
	}
	return *o.AsPathAccessList
}

// GetAsPathAccessListOk returns a tuple with the AsPathAccessList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AspathaccesslistsPutRequest) GetAsPathAccessListOk() (*map[string]AspathaccesslistsPutRequestAsPathAccessListValue, bool) {
	if o == nil || IsNil(o.AsPathAccessList) {
		return nil, false
	}
	return o.AsPathAccessList, true
}

// HasAsPathAccessList returns a boolean if a field has been set.
func (o *AspathaccesslistsPutRequest) HasAsPathAccessList() bool {
	if o != nil && !IsNil(o.AsPathAccessList) {
		return true
	}

	return false
}

// SetAsPathAccessList gets a reference to the given map[string]AspathaccesslistsPutRequestAsPathAccessListValue and assigns it to the AsPathAccessList field.
func (o *AspathaccesslistsPutRequest) SetAsPathAccessList(v map[string]AspathaccesslistsPutRequestAsPathAccessListValue) {
	o.AsPathAccessList = &v
}

func (o AspathaccesslistsPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AspathaccesslistsPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AsPathAccessList) {
		toSerialize["as_path_access_list"] = o.AsPathAccessList
	}
	return toSerialize, nil
}

type NullableAspathaccesslistsPutRequest struct {
	value *AspathaccesslistsPutRequest
	isSet bool
}

func (v NullableAspathaccesslistsPutRequest) Get() *AspathaccesslistsPutRequest {
	return v.value
}

func (v *NullableAspathaccesslistsPutRequest) Set(val *AspathaccesslistsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAspathaccesslistsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAspathaccesslistsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAspathaccesslistsPutRequest(val *AspathaccesslistsPutRequest) *NullableAspathaccesslistsPutRequest {
	return &NullableAspathaccesslistsPutRequest{value: val, isSet: true}
}

func (v NullableAspathaccesslistsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAspathaccesslistsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


