/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestRouteMapRouteMapName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestRouteMapRouteMapName{}

// ConfigPutRequestRouteMapRouteMapName struct for ConfigPutRequestRouteMapRouteMapName
type ConfigPutRequestRouteMapRouteMapName struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	RouteMapClauses []ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner `json:"route_map_clauses,omitempty"`
	ObjectProperties *ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties `json:"object_properties,omitempty"`
}

// NewConfigPutRequestRouteMapRouteMapName instantiates a new ConfigPutRequestRouteMapRouteMapName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestRouteMapRouteMapName() *ConfigPutRequestRouteMapRouteMapName {
	this := ConfigPutRequestRouteMapRouteMapName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// NewConfigPutRequestRouteMapRouteMapNameWithDefaults instantiates a new ConfigPutRequestRouteMapRouteMapName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestRouteMapRouteMapNameWithDefaults() *ConfigPutRequestRouteMapRouteMapName {
	this := ConfigPutRequestRouteMapRouteMapName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigPutRequestRouteMapRouteMapName) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigPutRequestRouteMapRouteMapName) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ConfigPutRequestRouteMapRouteMapName) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ConfigPutRequestRouteMapRouteMapName) SetEnable(v bool) {
	o.Enable = &v
}

// GetRouteMapClauses returns the RouteMapClauses field value if set, zero value otherwise.
func (o *ConfigPutRequestRouteMapRouteMapName) GetRouteMapClauses() []ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner {
	if o == nil || IsNil(o.RouteMapClauses) {
		var ret []ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner
		return ret
	}
	return o.RouteMapClauses
}

// GetRouteMapClausesOk returns a tuple with the RouteMapClauses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) GetRouteMapClausesOk() ([]ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner, bool) {
	if o == nil || IsNil(o.RouteMapClauses) {
		return nil, false
	}
	return o.RouteMapClauses, true
}

// HasRouteMapClauses returns a boolean if a field has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) HasRouteMapClauses() bool {
	if o != nil && !IsNil(o.RouteMapClauses) {
		return true
	}

	return false
}

// SetRouteMapClauses gets a reference to the given []ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner and assigns it to the RouteMapClauses field.
func (o *ConfigPutRequestRouteMapRouteMapName) SetRouteMapClauses(v []ConfigPutRequestRouteMapRouteMapNameRouteMapClausesInner) {
	o.RouteMapClauses = v
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *ConfigPutRequestRouteMapRouteMapName) GetObjectProperties() ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) GetObjectPropertiesOk() (*ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *ConfigPutRequestRouteMapRouteMapName) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties and assigns it to the ObjectProperties field.
func (o *ConfigPutRequestRouteMapRouteMapName) SetObjectProperties(v ConfigPutRequestIpv6FilterIpv6FilterNameObjectProperties) {
	o.ObjectProperties = &v
}

func (o ConfigPutRequestRouteMapRouteMapName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestRouteMapRouteMapName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.RouteMapClauses) {
		toSerialize["route_map_clauses"] = o.RouteMapClauses
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableConfigPutRequestRouteMapRouteMapName struct {
	value *ConfigPutRequestRouteMapRouteMapName
	isSet bool
}

func (v NullableConfigPutRequestRouteMapRouteMapName) Get() *ConfigPutRequestRouteMapRouteMapName {
	return v.value
}

func (v *NullableConfigPutRequestRouteMapRouteMapName) Set(val *ConfigPutRequestRouteMapRouteMapName) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestRouteMapRouteMapName) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestRouteMapRouteMapName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestRouteMapRouteMapName(val *ConfigPutRequestRouteMapRouteMapName) *NullableConfigPutRequestRouteMapRouteMapName {
	return &NullableConfigPutRequestRouteMapRouteMapName{value: val, isSet: true}
}

func (v NullableConfigPutRequestRouteMapRouteMapName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestRouteMapRouteMapName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


