/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner{}

// ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner struct for ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner
type ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner struct {
	// Enable row
	RowNumEnable *bool `json:"row_num_enable,omitempty"`
	// Connect a Service
	RowNumService *string `json:"row_num_service,omitempty"`
	// Object type for row_num_service field
	RowNumServiceRefType *string `json:"row_num_service_ref_type_,omitempty"`
	// Choose an external vlan
	RowNumExternalVlan NullableInt32 `json:"row_num_external_vlan,omitempty"`
	// Speed of ingress (Mbps)
	RowNumLimitIn NullableInt32 `json:"row_num_limit_in,omitempty"`
	// Speed of egress (Mbps)
	RowNumLimitOut NullableInt32 `json:"row_num_limit_out,omitempty"`
	// The index identifying the object. Zero if you want to add an object to the list.
	Index *int32 `json:"index,omitempty"`
}

// NewConfigPutRequestServicePortProfileServicePortProfileNameServicesInner instantiates a new ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestServicePortProfileServicePortProfileNameServicesInner() *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner {
	this := ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner{}
	var rowNumEnable bool = false
	this.RowNumEnable = &rowNumEnable
	var rowNumService string = ""
	this.RowNumService = &rowNumService
	var rowNumLimitOut int32 = 1000
	this.RowNumLimitOut = *NewNullableInt32(&rowNumLimitOut)
	return &this
}

// NewConfigPutRequestServicePortProfileServicePortProfileNameServicesInnerWithDefaults instantiates a new ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestServicePortProfileServicePortProfileNameServicesInnerWithDefaults() *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner {
	this := ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner{}
	var rowNumEnable bool = false
	this.RowNumEnable = &rowNumEnable
	var rowNumService string = ""
	this.RowNumService = &rowNumService
	var rowNumLimitOut int32 = 1000
	this.RowNumLimitOut = *NewNullableInt32(&rowNumLimitOut)
	return &this
}

// GetRowNumEnable returns the RowNumEnable field value if set, zero value otherwise.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumEnable() bool {
	if o == nil || IsNil(o.RowNumEnable) {
		var ret bool
		return ret
	}
	return *o.RowNumEnable
}

// GetRowNumEnableOk returns a tuple with the RowNumEnable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.RowNumEnable) {
		return nil, false
	}
	return o.RowNumEnable, true
}

// HasRowNumEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumEnable() bool {
	if o != nil && !IsNil(o.RowNumEnable) {
		return true
	}

	return false
}

// SetRowNumEnable gets a reference to the given bool and assigns it to the RowNumEnable field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumEnable(v bool) {
	o.RowNumEnable = &v
}

// GetRowNumService returns the RowNumService field value if set, zero value otherwise.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumService() string {
	if o == nil || IsNil(o.RowNumService) {
		var ret string
		return ret
	}
	return *o.RowNumService
}

// GetRowNumServiceOk returns a tuple with the RowNumService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumServiceOk() (*string, bool) {
	if o == nil || IsNil(o.RowNumService) {
		return nil, false
	}
	return o.RowNumService, true
}

// HasRowNumService returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumService() bool {
	if o != nil && !IsNil(o.RowNumService) {
		return true
	}

	return false
}

// SetRowNumService gets a reference to the given string and assigns it to the RowNumService field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumService(v string) {
	o.RowNumService = &v
}

// GetRowNumServiceRefType returns the RowNumServiceRefType field value if set, zero value otherwise.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumServiceRefType() string {
	if o == nil || IsNil(o.RowNumServiceRefType) {
		var ret string
		return ret
	}
	return *o.RowNumServiceRefType
}

// GetRowNumServiceRefTypeOk returns a tuple with the RowNumServiceRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumServiceRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.RowNumServiceRefType) {
		return nil, false
	}
	return o.RowNumServiceRefType, true
}

// HasRowNumServiceRefType returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumServiceRefType() bool {
	if o != nil && !IsNil(o.RowNumServiceRefType) {
		return true
	}

	return false
}

// SetRowNumServiceRefType gets a reference to the given string and assigns it to the RowNumServiceRefType field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumServiceRefType(v string) {
	o.RowNumServiceRefType = &v
}

// GetRowNumExternalVlan returns the RowNumExternalVlan field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumExternalVlan() int32 {
	if o == nil || IsNil(o.RowNumExternalVlan.Get()) {
		var ret int32
		return ret
	}
	return *o.RowNumExternalVlan.Get()
}

// GetRowNumExternalVlanOk returns a tuple with the RowNumExternalVlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumExternalVlanOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RowNumExternalVlan.Get(), o.RowNumExternalVlan.IsSet()
}

// HasRowNumExternalVlan returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumExternalVlan() bool {
	if o != nil && o.RowNumExternalVlan.IsSet() {
		return true
	}

	return false
}

// SetRowNumExternalVlan gets a reference to the given NullableInt32 and assigns it to the RowNumExternalVlan field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumExternalVlan(v int32) {
	o.RowNumExternalVlan.Set(&v)
}
// SetRowNumExternalVlanNil sets the value for RowNumExternalVlan to be an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumExternalVlanNil() {
	o.RowNumExternalVlan.Set(nil)
}

// UnsetRowNumExternalVlan ensures that no value is present for RowNumExternalVlan, not even an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) UnsetRowNumExternalVlan() {
	o.RowNumExternalVlan.Unset()
}

// GetRowNumLimitIn returns the RowNumLimitIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumLimitIn() int32 {
	if o == nil || IsNil(o.RowNumLimitIn.Get()) {
		var ret int32
		return ret
	}
	return *o.RowNumLimitIn.Get()
}

// GetRowNumLimitInOk returns a tuple with the RowNumLimitIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumLimitInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RowNumLimitIn.Get(), o.RowNumLimitIn.IsSet()
}

// HasRowNumLimitIn returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumLimitIn() bool {
	if o != nil && o.RowNumLimitIn.IsSet() {
		return true
	}

	return false
}

// SetRowNumLimitIn gets a reference to the given NullableInt32 and assigns it to the RowNumLimitIn field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumLimitIn(v int32) {
	o.RowNumLimitIn.Set(&v)
}
// SetRowNumLimitInNil sets the value for RowNumLimitIn to be an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumLimitInNil() {
	o.RowNumLimitIn.Set(nil)
}

// UnsetRowNumLimitIn ensures that no value is present for RowNumLimitIn, not even an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) UnsetRowNumLimitIn() {
	o.RowNumLimitIn.Unset()
}

// GetRowNumLimitOut returns the RowNumLimitOut field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumLimitOut() int32 {
	if o == nil || IsNil(o.RowNumLimitOut.Get()) {
		var ret int32
		return ret
	}
	return *o.RowNumLimitOut.Get()
}

// GetRowNumLimitOutOk returns a tuple with the RowNumLimitOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetRowNumLimitOutOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RowNumLimitOut.Get(), o.RowNumLimitOut.IsSet()
}

// HasRowNumLimitOut returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasRowNumLimitOut() bool {
	if o != nil && o.RowNumLimitOut.IsSet() {
		return true
	}

	return false
}

// SetRowNumLimitOut gets a reference to the given NullableInt32 and assigns it to the RowNumLimitOut field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumLimitOut(v int32) {
	o.RowNumLimitOut.Set(&v)
}
// SetRowNumLimitOutNil sets the value for RowNumLimitOut to be an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetRowNumLimitOutNil() {
	o.RowNumLimitOut.Set(nil)
}

// UnsetRowNumLimitOut ensures that no value is present for RowNumLimitOut, not even an explicit nil
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) UnsetRowNumLimitOut() {
	o.RowNumLimitOut.Unset()
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) SetIndex(v int32) {
	o.Index = &v
}

func (o ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RowNumEnable) {
		toSerialize["row_num_enable"] = o.RowNumEnable
	}
	if !IsNil(o.RowNumService) {
		toSerialize["row_num_service"] = o.RowNumService
	}
	if !IsNil(o.RowNumServiceRefType) {
		toSerialize["row_num_service_ref_type_"] = o.RowNumServiceRefType
	}
	if o.RowNumExternalVlan.IsSet() {
		toSerialize["row_num_external_vlan"] = o.RowNumExternalVlan.Get()
	}
	if o.RowNumLimitIn.IsSet() {
		toSerialize["row_num_limit_in"] = o.RowNumLimitIn.Get()
	}
	if o.RowNumLimitOut.IsSet() {
		toSerialize["row_num_limit_out"] = o.RowNumLimitOut.Get()
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	return toSerialize, nil
}

type NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner struct {
	value *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner
	isSet bool
}

func (v NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) Get() *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner {
	return v.value
}

func (v *NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) Set(val *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner(val *ConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) *NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner {
	return &NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner{value: val, isSet: true}
}

func (v NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestServicePortProfileServicePortProfileNameServicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


