/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestTenantTenantName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestTenantTenantName{}

// ConfigPutRequestTenantTenantName struct for ConfigPutRequestTenantTenantName
type ConfigPutRequestTenantTenantName struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	// VNI value used to transport traffic between services of a Tenant 
	Layer3Vni NullableInt32 `json:"layer_3_vni,omitempty"`
	// Whether or not the value in layer_3_vni field has been automatically assigned or not. Set to false and change layer_3_vni value to edit.
	Layer3VniAutoAssigned *bool `json:"layer_3_vni_auto_assigned_,omitempty"`
	// VLAN value used to transport traffic between services of a Tenant 
	Layer3Vlan NullableInt32 `json:"layer_3_vlan,omitempty"`
	// Whether or not the value in layer_3_vlan field has been automatically assigned or not. Set to false and change layer_3_vlan value to edit.
	Layer3VlanAutoAssigned *bool `json:"layer_3_vlan_auto_assigned_,omitempty"`
	// Range of IP addresses (represented in IP subnet format) used to configure the source IP of each DHCP Relay on each switch that this Tenant is provisioned on.
	DhcpRelaySourceIpsSubnet *string `json:"dhcp_relay_source_ips_subnet,omitempty"`
	// Route Distinguishers are used to maintain uniqueness among identical routes from different routers.  If set, then routes from this Tenant will be identified with this Route Distinguisher (BGP Community).  It should be two numbers separated by a colon.
	RouteDistinguisher *string `json:"route_distinguisher,omitempty"`
	// A route-target (BGP Community) to attach while importing routes into the current tenant. It should be a comma-separated list of BGP Communities: each Community being two numbers separated by a colon.
	RouteTargetImport *string `json:"route_target_import,omitempty"`
	// A route-target (BGP Community) to attach while exporting routes from the current tenant. It should be a comma-separated list of BGP Communities: each Community being two numbers separated by a colon.
	RouteTargetExport *string `json:"route_target_export,omitempty"`
	// A route-map applied to routes imported into the current tenant from other tenants with the purpose of filtering or modifying the routes
	ImportRouteMap *string `json:"import_route_map,omitempty"`
	// Object type for import_route_map field
	ImportRouteMapRefType *string `json:"import_route_map_ref_type_,omitempty"`
	// A route-map applied to routes exported into the current tenant from other tenants with the purpose of filtering or modifying the routes
	ExportRouteMap *string `json:"export_route_map,omitempty"`
	// Object type for export_route_map field
	ExportRouteMapRefType *string `json:"export_route_map_ref_type_,omitempty"`
	// Virtual Routing and Forwarding instance name associated to tenants 
	VrfName *string `json:"vrf_name,omitempty"`
	// Whether or not the value in vrf_name field has been automatically assigned or not. Set to false and change vrf_name value to edit.
	VrfNameAutoAssigned *bool `json:"vrf_name_auto_assigned_,omitempty"`
	RouteTenants []ConfigPutRequestTenantTenantNameRouteTenantsInner `json:"route_tenants,omitempty"`
	ObjectProperties *ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties `json:"object_properties,omitempty"`
}

// NewConfigPutRequestTenantTenantName instantiates a new ConfigPutRequestTenantTenantName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestTenantTenantName() *ConfigPutRequestTenantTenantName {
	this := ConfigPutRequestTenantTenantName{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var dhcpRelaySourceIpsSubnet string = ""
	this.DhcpRelaySourceIpsSubnet = &dhcpRelaySourceIpsSubnet
	var routeDistinguisher string = ""
	this.RouteDistinguisher = &routeDistinguisher
	var routeTargetImport string = ""
	this.RouteTargetImport = &routeTargetImport
	var routeTargetExport string = ""
	this.RouteTargetExport = &routeTargetExport
	var importRouteMap string = ""
	this.ImportRouteMap = &importRouteMap
	var exportRouteMap string = ""
	this.ExportRouteMap = &exportRouteMap
	var vrfName string = "(auto)"
	this.VrfName = &vrfName
	return &this
}

// NewConfigPutRequestTenantTenantNameWithDefaults instantiates a new ConfigPutRequestTenantTenantName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestTenantTenantNameWithDefaults() *ConfigPutRequestTenantTenantName {
	this := ConfigPutRequestTenantTenantName{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var dhcpRelaySourceIpsSubnet string = ""
	this.DhcpRelaySourceIpsSubnet = &dhcpRelaySourceIpsSubnet
	var routeDistinguisher string = ""
	this.RouteDistinguisher = &routeDistinguisher
	var routeTargetImport string = ""
	this.RouteTargetImport = &routeTargetImport
	var routeTargetExport string = ""
	this.RouteTargetExport = &routeTargetExport
	var importRouteMap string = ""
	this.ImportRouteMap = &importRouteMap
	var exportRouteMap string = ""
	this.ExportRouteMap = &exportRouteMap
	var vrfName string = "(auto)"
	this.VrfName = &vrfName
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigPutRequestTenantTenantName) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ConfigPutRequestTenantTenantName) SetEnable(v bool) {
	o.Enable = &v
}

// GetLayer3Vni returns the Layer3Vni field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigPutRequestTenantTenantName) GetLayer3Vni() int32 {
	if o == nil || IsNil(o.Layer3Vni.Get()) {
		var ret int32
		return ret
	}
	return *o.Layer3Vni.Get()
}

// GetLayer3VniOk returns a tuple with the Layer3Vni field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigPutRequestTenantTenantName) GetLayer3VniOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layer3Vni.Get(), o.Layer3Vni.IsSet()
}

// HasLayer3Vni returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasLayer3Vni() bool {
	if o != nil && o.Layer3Vni.IsSet() {
		return true
	}

	return false
}

// SetLayer3Vni gets a reference to the given NullableInt32 and assigns it to the Layer3Vni field.
func (o *ConfigPutRequestTenantTenantName) SetLayer3Vni(v int32) {
	o.Layer3Vni.Set(&v)
}
// SetLayer3VniNil sets the value for Layer3Vni to be an explicit nil
func (o *ConfigPutRequestTenantTenantName) SetLayer3VniNil() {
	o.Layer3Vni.Set(nil)
}

// UnsetLayer3Vni ensures that no value is present for Layer3Vni, not even an explicit nil
func (o *ConfigPutRequestTenantTenantName) UnsetLayer3Vni() {
	o.Layer3Vni.Unset()
}

// GetLayer3VniAutoAssigned returns the Layer3VniAutoAssigned field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetLayer3VniAutoAssigned() bool {
	if o == nil || IsNil(o.Layer3VniAutoAssigned) {
		var ret bool
		return ret
	}
	return *o.Layer3VniAutoAssigned
}

// GetLayer3VniAutoAssignedOk returns a tuple with the Layer3VniAutoAssigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetLayer3VniAutoAssignedOk() (*bool, bool) {
	if o == nil || IsNil(o.Layer3VniAutoAssigned) {
		return nil, false
	}
	return o.Layer3VniAutoAssigned, true
}

// HasLayer3VniAutoAssigned returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasLayer3VniAutoAssigned() bool {
	if o != nil && !IsNil(o.Layer3VniAutoAssigned) {
		return true
	}

	return false
}

// SetLayer3VniAutoAssigned gets a reference to the given bool and assigns it to the Layer3VniAutoAssigned field.
func (o *ConfigPutRequestTenantTenantName) SetLayer3VniAutoAssigned(v bool) {
	o.Layer3VniAutoAssigned = &v
}

// GetLayer3Vlan returns the Layer3Vlan field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigPutRequestTenantTenantName) GetLayer3Vlan() int32 {
	if o == nil || IsNil(o.Layer3Vlan.Get()) {
		var ret int32
		return ret
	}
	return *o.Layer3Vlan.Get()
}

// GetLayer3VlanOk returns a tuple with the Layer3Vlan field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigPutRequestTenantTenantName) GetLayer3VlanOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Layer3Vlan.Get(), o.Layer3Vlan.IsSet()
}

// HasLayer3Vlan returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasLayer3Vlan() bool {
	if o != nil && o.Layer3Vlan.IsSet() {
		return true
	}

	return false
}

// SetLayer3Vlan gets a reference to the given NullableInt32 and assigns it to the Layer3Vlan field.
func (o *ConfigPutRequestTenantTenantName) SetLayer3Vlan(v int32) {
	o.Layer3Vlan.Set(&v)
}
// SetLayer3VlanNil sets the value for Layer3Vlan to be an explicit nil
func (o *ConfigPutRequestTenantTenantName) SetLayer3VlanNil() {
	o.Layer3Vlan.Set(nil)
}

// UnsetLayer3Vlan ensures that no value is present for Layer3Vlan, not even an explicit nil
func (o *ConfigPutRequestTenantTenantName) UnsetLayer3Vlan() {
	o.Layer3Vlan.Unset()
}

// GetLayer3VlanAutoAssigned returns the Layer3VlanAutoAssigned field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetLayer3VlanAutoAssigned() bool {
	if o == nil || IsNil(o.Layer3VlanAutoAssigned) {
		var ret bool
		return ret
	}
	return *o.Layer3VlanAutoAssigned
}

// GetLayer3VlanAutoAssignedOk returns a tuple with the Layer3VlanAutoAssigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetLayer3VlanAutoAssignedOk() (*bool, bool) {
	if o == nil || IsNil(o.Layer3VlanAutoAssigned) {
		return nil, false
	}
	return o.Layer3VlanAutoAssigned, true
}

// HasLayer3VlanAutoAssigned returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasLayer3VlanAutoAssigned() bool {
	if o != nil && !IsNil(o.Layer3VlanAutoAssigned) {
		return true
	}

	return false
}

// SetLayer3VlanAutoAssigned gets a reference to the given bool and assigns it to the Layer3VlanAutoAssigned field.
func (o *ConfigPutRequestTenantTenantName) SetLayer3VlanAutoAssigned(v bool) {
	o.Layer3VlanAutoAssigned = &v
}

// GetDhcpRelaySourceIpsSubnet returns the DhcpRelaySourceIpsSubnet field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetDhcpRelaySourceIpsSubnet() string {
	if o == nil || IsNil(o.DhcpRelaySourceIpsSubnet) {
		var ret string
		return ret
	}
	return *o.DhcpRelaySourceIpsSubnet
}

// GetDhcpRelaySourceIpsSubnetOk returns a tuple with the DhcpRelaySourceIpsSubnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetDhcpRelaySourceIpsSubnetOk() (*string, bool) {
	if o == nil || IsNil(o.DhcpRelaySourceIpsSubnet) {
		return nil, false
	}
	return o.DhcpRelaySourceIpsSubnet, true
}

// HasDhcpRelaySourceIpsSubnet returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasDhcpRelaySourceIpsSubnet() bool {
	if o != nil && !IsNil(o.DhcpRelaySourceIpsSubnet) {
		return true
	}

	return false
}

// SetDhcpRelaySourceIpsSubnet gets a reference to the given string and assigns it to the DhcpRelaySourceIpsSubnet field.
func (o *ConfigPutRequestTenantTenantName) SetDhcpRelaySourceIpsSubnet(v string) {
	o.DhcpRelaySourceIpsSubnet = &v
}

// GetRouteDistinguisher returns the RouteDistinguisher field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetRouteDistinguisher() string {
	if o == nil || IsNil(o.RouteDistinguisher) {
		var ret string
		return ret
	}
	return *o.RouteDistinguisher
}

// GetRouteDistinguisherOk returns a tuple with the RouteDistinguisher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetRouteDistinguisherOk() (*string, bool) {
	if o == nil || IsNil(o.RouteDistinguisher) {
		return nil, false
	}
	return o.RouteDistinguisher, true
}

// HasRouteDistinguisher returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasRouteDistinguisher() bool {
	if o != nil && !IsNil(o.RouteDistinguisher) {
		return true
	}

	return false
}

// SetRouteDistinguisher gets a reference to the given string and assigns it to the RouteDistinguisher field.
func (o *ConfigPutRequestTenantTenantName) SetRouteDistinguisher(v string) {
	o.RouteDistinguisher = &v
}

// GetRouteTargetImport returns the RouteTargetImport field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetRouteTargetImport() string {
	if o == nil || IsNil(o.RouteTargetImport) {
		var ret string
		return ret
	}
	return *o.RouteTargetImport
}

// GetRouteTargetImportOk returns a tuple with the RouteTargetImport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetRouteTargetImportOk() (*string, bool) {
	if o == nil || IsNil(o.RouteTargetImport) {
		return nil, false
	}
	return o.RouteTargetImport, true
}

// HasRouteTargetImport returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasRouteTargetImport() bool {
	if o != nil && !IsNil(o.RouteTargetImport) {
		return true
	}

	return false
}

// SetRouteTargetImport gets a reference to the given string and assigns it to the RouteTargetImport field.
func (o *ConfigPutRequestTenantTenantName) SetRouteTargetImport(v string) {
	o.RouteTargetImport = &v
}

// GetRouteTargetExport returns the RouteTargetExport field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetRouteTargetExport() string {
	if o == nil || IsNil(o.RouteTargetExport) {
		var ret string
		return ret
	}
	return *o.RouteTargetExport
}

// GetRouteTargetExportOk returns a tuple with the RouteTargetExport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetRouteTargetExportOk() (*string, bool) {
	if o == nil || IsNil(o.RouteTargetExport) {
		return nil, false
	}
	return o.RouteTargetExport, true
}

// HasRouteTargetExport returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasRouteTargetExport() bool {
	if o != nil && !IsNil(o.RouteTargetExport) {
		return true
	}

	return false
}

// SetRouteTargetExport gets a reference to the given string and assigns it to the RouteTargetExport field.
func (o *ConfigPutRequestTenantTenantName) SetRouteTargetExport(v string) {
	o.RouteTargetExport = &v
}

// GetImportRouteMap returns the ImportRouteMap field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetImportRouteMap() string {
	if o == nil || IsNil(o.ImportRouteMap) {
		var ret string
		return ret
	}
	return *o.ImportRouteMap
}

// GetImportRouteMapOk returns a tuple with the ImportRouteMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetImportRouteMapOk() (*string, bool) {
	if o == nil || IsNil(o.ImportRouteMap) {
		return nil, false
	}
	return o.ImportRouteMap, true
}

// HasImportRouteMap returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasImportRouteMap() bool {
	if o != nil && !IsNil(o.ImportRouteMap) {
		return true
	}

	return false
}

// SetImportRouteMap gets a reference to the given string and assigns it to the ImportRouteMap field.
func (o *ConfigPutRequestTenantTenantName) SetImportRouteMap(v string) {
	o.ImportRouteMap = &v
}

// GetImportRouteMapRefType returns the ImportRouteMapRefType field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetImportRouteMapRefType() string {
	if o == nil || IsNil(o.ImportRouteMapRefType) {
		var ret string
		return ret
	}
	return *o.ImportRouteMapRefType
}

// GetImportRouteMapRefTypeOk returns a tuple with the ImportRouteMapRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetImportRouteMapRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ImportRouteMapRefType) {
		return nil, false
	}
	return o.ImportRouteMapRefType, true
}

// HasImportRouteMapRefType returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasImportRouteMapRefType() bool {
	if o != nil && !IsNil(o.ImportRouteMapRefType) {
		return true
	}

	return false
}

// SetImportRouteMapRefType gets a reference to the given string and assigns it to the ImportRouteMapRefType field.
func (o *ConfigPutRequestTenantTenantName) SetImportRouteMapRefType(v string) {
	o.ImportRouteMapRefType = &v
}

// GetExportRouteMap returns the ExportRouteMap field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetExportRouteMap() string {
	if o == nil || IsNil(o.ExportRouteMap) {
		var ret string
		return ret
	}
	return *o.ExportRouteMap
}

// GetExportRouteMapOk returns a tuple with the ExportRouteMap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetExportRouteMapOk() (*string, bool) {
	if o == nil || IsNil(o.ExportRouteMap) {
		return nil, false
	}
	return o.ExportRouteMap, true
}

// HasExportRouteMap returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasExportRouteMap() bool {
	if o != nil && !IsNil(o.ExportRouteMap) {
		return true
	}

	return false
}

// SetExportRouteMap gets a reference to the given string and assigns it to the ExportRouteMap field.
func (o *ConfigPutRequestTenantTenantName) SetExportRouteMap(v string) {
	o.ExportRouteMap = &v
}

// GetExportRouteMapRefType returns the ExportRouteMapRefType field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetExportRouteMapRefType() string {
	if o == nil || IsNil(o.ExportRouteMapRefType) {
		var ret string
		return ret
	}
	return *o.ExportRouteMapRefType
}

// GetExportRouteMapRefTypeOk returns a tuple with the ExportRouteMapRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetExportRouteMapRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ExportRouteMapRefType) {
		return nil, false
	}
	return o.ExportRouteMapRefType, true
}

// HasExportRouteMapRefType returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasExportRouteMapRefType() bool {
	if o != nil && !IsNil(o.ExportRouteMapRefType) {
		return true
	}

	return false
}

// SetExportRouteMapRefType gets a reference to the given string and assigns it to the ExportRouteMapRefType field.
func (o *ConfigPutRequestTenantTenantName) SetExportRouteMapRefType(v string) {
	o.ExportRouteMapRefType = &v
}

// GetVrfName returns the VrfName field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetVrfName() string {
	if o == nil || IsNil(o.VrfName) {
		var ret string
		return ret
	}
	return *o.VrfName
}

// GetVrfNameOk returns a tuple with the VrfName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetVrfNameOk() (*string, bool) {
	if o == nil || IsNil(o.VrfName) {
		return nil, false
	}
	return o.VrfName, true
}

// HasVrfName returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasVrfName() bool {
	if o != nil && !IsNil(o.VrfName) {
		return true
	}

	return false
}

// SetVrfName gets a reference to the given string and assigns it to the VrfName field.
func (o *ConfigPutRequestTenantTenantName) SetVrfName(v string) {
	o.VrfName = &v
}

// GetVrfNameAutoAssigned returns the VrfNameAutoAssigned field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetVrfNameAutoAssigned() bool {
	if o == nil || IsNil(o.VrfNameAutoAssigned) {
		var ret bool
		return ret
	}
	return *o.VrfNameAutoAssigned
}

// GetVrfNameAutoAssignedOk returns a tuple with the VrfNameAutoAssigned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetVrfNameAutoAssignedOk() (*bool, bool) {
	if o == nil || IsNil(o.VrfNameAutoAssigned) {
		return nil, false
	}
	return o.VrfNameAutoAssigned, true
}

// HasVrfNameAutoAssigned returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasVrfNameAutoAssigned() bool {
	if o != nil && !IsNil(o.VrfNameAutoAssigned) {
		return true
	}

	return false
}

// SetVrfNameAutoAssigned gets a reference to the given bool and assigns it to the VrfNameAutoAssigned field.
func (o *ConfigPutRequestTenantTenantName) SetVrfNameAutoAssigned(v bool) {
	o.VrfNameAutoAssigned = &v
}

// GetRouteTenants returns the RouteTenants field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetRouteTenants() []ConfigPutRequestTenantTenantNameRouteTenantsInner {
	if o == nil || IsNil(o.RouteTenants) {
		var ret []ConfigPutRequestTenantTenantNameRouteTenantsInner
		return ret
	}
	return o.RouteTenants
}

// GetRouteTenantsOk returns a tuple with the RouteTenants field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetRouteTenantsOk() ([]ConfigPutRequestTenantTenantNameRouteTenantsInner, bool) {
	if o == nil || IsNil(o.RouteTenants) {
		return nil, false
	}
	return o.RouteTenants, true
}

// HasRouteTenants returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasRouteTenants() bool {
	if o != nil && !IsNil(o.RouteTenants) {
		return true
	}

	return false
}

// SetRouteTenants gets a reference to the given []ConfigPutRequestTenantTenantNameRouteTenantsInner and assigns it to the RouteTenants field.
func (o *ConfigPutRequestTenantTenantName) SetRouteTenants(v []ConfigPutRequestTenantTenantNameRouteTenantsInner) {
	o.RouteTenants = v
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *ConfigPutRequestTenantTenantName) GetObjectProperties() ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestTenantTenantName) GetObjectPropertiesOk() (*ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *ConfigPutRequestTenantTenantName) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties and assigns it to the ObjectProperties field.
func (o *ConfigPutRequestTenantTenantName) SetObjectProperties(v ConfigPutRequestEthDeviceProfilesEthDeviceProfilesNameObjectProperties) {
	o.ObjectProperties = &v
}

func (o ConfigPutRequestTenantTenantName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestTenantTenantName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if o.Layer3Vni.IsSet() {
		toSerialize["layer_3_vni"] = o.Layer3Vni.Get()
	}
	if !IsNil(o.Layer3VniAutoAssigned) {
		toSerialize["layer_3_vni_auto_assigned_"] = o.Layer3VniAutoAssigned
	}
	if o.Layer3Vlan.IsSet() {
		toSerialize["layer_3_vlan"] = o.Layer3Vlan.Get()
	}
	if !IsNil(o.Layer3VlanAutoAssigned) {
		toSerialize["layer_3_vlan_auto_assigned_"] = o.Layer3VlanAutoAssigned
	}
	if !IsNil(o.DhcpRelaySourceIpsSubnet) {
		toSerialize["dhcp_relay_source_ips_subnet"] = o.DhcpRelaySourceIpsSubnet
	}
	if !IsNil(o.RouteDistinguisher) {
		toSerialize["route_distinguisher"] = o.RouteDistinguisher
	}
	if !IsNil(o.RouteTargetImport) {
		toSerialize["route_target_import"] = o.RouteTargetImport
	}
	if !IsNil(o.RouteTargetExport) {
		toSerialize["route_target_export"] = o.RouteTargetExport
	}
	if !IsNil(o.ImportRouteMap) {
		toSerialize["import_route_map"] = o.ImportRouteMap
	}
	if !IsNil(o.ImportRouteMapRefType) {
		toSerialize["import_route_map_ref_type_"] = o.ImportRouteMapRefType
	}
	if !IsNil(o.ExportRouteMap) {
		toSerialize["export_route_map"] = o.ExportRouteMap
	}
	if !IsNil(o.ExportRouteMapRefType) {
		toSerialize["export_route_map_ref_type_"] = o.ExportRouteMapRefType
	}
	if !IsNil(o.VrfName) {
		toSerialize["vrf_name"] = o.VrfName
	}
	if !IsNil(o.VrfNameAutoAssigned) {
		toSerialize["vrf_name_auto_assigned_"] = o.VrfNameAutoAssigned
	}
	if !IsNil(o.RouteTenants) {
		toSerialize["route_tenants"] = o.RouteTenants
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableConfigPutRequestTenantTenantName struct {
	value *ConfigPutRequestTenantTenantName
	isSet bool
}

func (v NullableConfigPutRequestTenantTenantName) Get() *ConfigPutRequestTenantTenantName {
	return v.value
}

func (v *NullableConfigPutRequestTenantTenantName) Set(val *ConfigPutRequestTenantTenantName) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestTenantTenantName) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestTenantTenantName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestTenantTenantName(val *ConfigPutRequestTenantTenantName) *NullableConfigPutRequestTenantTenantName {
	return &NullableConfigPutRequestTenantTenantName{value: val, isSet: true}
}

func (v NullableConfigPutRequestTenantTenantName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestTenantTenantName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


