/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 6.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LdapprofilesPutRequestLdapProfileValueLdapServersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LdapprofilesPutRequestLdapProfileValueLdapServersInner{}

// LdapprofilesPutRequestLdapProfileValueLdapServersInner struct for LdapprofilesPutRequestLdapProfileValueLdapServersInner
type LdapprofilesPutRequestLdapProfileValueLdapServersInner struct {
	// Enable this LDAP server entry
	Enabled *bool `json:"enabled,omitempty"`
	// IPv4, IPv6, or DNS hostname for LDAP server
	Server *string `json:"server,omitempty"`
	// Server port (overrides global default port)
	Port NullableInt32 `json:"port,omitempty"`
	// Which LDAP client(s) use this server
	UseType *string `json:"use_type,omitempty"`
	// Server priority (1-99, lower = higher priority)
	Priority NullableInt32 `json:"priority,omitempty"`
	// Per-server TLS mode (overrides global setting)
	SslTlsMode *string `json:"ssl_tls_mode,omitempty"`
	// Per-server retransmit attempts (0-10)
	RetransmitAttempts NullableInt32 `json:"retransmit_attempts,omitempty"`
	// The index identifying the object. Zero if you want to add an object to the list.
	Index *int32 `json:"index,omitempty"`
}

// NewLdapprofilesPutRequestLdapProfileValueLdapServersInner instantiates a new LdapprofilesPutRequestLdapProfileValueLdapServersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLdapprofilesPutRequestLdapProfileValueLdapServersInner() *LdapprofilesPutRequestLdapProfileValueLdapServersInner {
	this := LdapprofilesPutRequestLdapProfileValueLdapServersInner{}
	var enabled bool = false
	this.Enabled = &enabled
	var server string = ""
	this.Server = &server
	var useType string = "all"
	this.UseType = &useType
	var sslTlsMode string = "off"
	this.SslTlsMode = &sslTlsMode
	return &this
}

// NewLdapprofilesPutRequestLdapProfileValueLdapServersInnerWithDefaults instantiates a new LdapprofilesPutRequestLdapProfileValueLdapServersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLdapprofilesPutRequestLdapProfileValueLdapServersInnerWithDefaults() *LdapprofilesPutRequestLdapProfileValueLdapServersInner {
	this := LdapprofilesPutRequestLdapProfileValueLdapServersInner{}
	var enabled bool = false
	this.Enabled = &enabled
	var server string = ""
	this.Server = &server
	var useType string = "all"
	this.UseType = &useType
	var sslTlsMode string = "off"
	this.SslTlsMode = &sslTlsMode
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetServer returns the Server field value if set, zero value otherwise.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetServer() string {
	if o == nil || IsNil(o.Server) {
		var ret string
		return ret
	}
	return *o.Server
}

// GetServerOk returns a tuple with the Server field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetServerOk() (*string, bool) {
	if o == nil || IsNil(o.Server) {
		return nil, false
	}
	return o.Server, true
}

// HasServer returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasServer() bool {
	if o != nil && !IsNil(o.Server) {
		return true
	}

	return false
}

// SetServer gets a reference to the given string and assigns it to the Server field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetServer(v string) {
	o.Server = &v
}

// GetPort returns the Port field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetPort() int32 {
	if o == nil || IsNil(o.Port.Get()) {
		var ret int32
		return ret
	}
	return *o.Port.Get()
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Port.Get(), o.Port.IsSet()
}

// HasPort returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasPort() bool {
	if o != nil && o.Port.IsSet() {
		return true
	}

	return false
}

// SetPort gets a reference to the given NullableInt32 and assigns it to the Port field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetPort(v int32) {
	o.Port.Set(&v)
}
// SetPortNil sets the value for Port to be an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetPortNil() {
	o.Port.Set(nil)
}

// UnsetPort ensures that no value is present for Port, not even an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) UnsetPort() {
	o.Port.Unset()
}

// GetUseType returns the UseType field value if set, zero value otherwise.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetUseType() string {
	if o == nil || IsNil(o.UseType) {
		var ret string
		return ret
	}
	return *o.UseType
}

// GetUseTypeOk returns a tuple with the UseType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetUseTypeOk() (*string, bool) {
	if o == nil || IsNil(o.UseType) {
		return nil, false
	}
	return o.UseType, true
}

// HasUseType returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasUseType() bool {
	if o != nil && !IsNil(o.UseType) {
		return true
	}

	return false
}

// SetUseType gets a reference to the given string and assigns it to the UseType field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetUseType(v string) {
	o.UseType = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetPriority() int32 {
	if o == nil || IsNil(o.Priority.Get()) {
		var ret int32
		return ret
	}
	return *o.Priority.Get()
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Priority.Get(), o.Priority.IsSet()
}

// HasPriority returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasPriority() bool {
	if o != nil && o.Priority.IsSet() {
		return true
	}

	return false
}

// SetPriority gets a reference to the given NullableInt32 and assigns it to the Priority field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetPriority(v int32) {
	o.Priority.Set(&v)
}
// SetPriorityNil sets the value for Priority to be an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetPriorityNil() {
	o.Priority.Set(nil)
}

// UnsetPriority ensures that no value is present for Priority, not even an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) UnsetPriority() {
	o.Priority.Unset()
}

// GetSslTlsMode returns the SslTlsMode field value if set, zero value otherwise.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetSslTlsMode() string {
	if o == nil || IsNil(o.SslTlsMode) {
		var ret string
		return ret
	}
	return *o.SslTlsMode
}

// GetSslTlsModeOk returns a tuple with the SslTlsMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetSslTlsModeOk() (*string, bool) {
	if o == nil || IsNil(o.SslTlsMode) {
		return nil, false
	}
	return o.SslTlsMode, true
}

// HasSslTlsMode returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasSslTlsMode() bool {
	if o != nil && !IsNil(o.SslTlsMode) {
		return true
	}

	return false
}

// SetSslTlsMode gets a reference to the given string and assigns it to the SslTlsMode field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetSslTlsMode(v string) {
	o.SslTlsMode = &v
}

// GetRetransmitAttempts returns the RetransmitAttempts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetRetransmitAttempts() int32 {
	if o == nil || IsNil(o.RetransmitAttempts.Get()) {
		var ret int32
		return ret
	}
	return *o.RetransmitAttempts.Get()
}

// GetRetransmitAttemptsOk returns a tuple with the RetransmitAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetRetransmitAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RetransmitAttempts.Get(), o.RetransmitAttempts.IsSet()
}

// HasRetransmitAttempts returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasRetransmitAttempts() bool {
	if o != nil && o.RetransmitAttempts.IsSet() {
		return true
	}

	return false
}

// SetRetransmitAttempts gets a reference to the given NullableInt32 and assigns it to the RetransmitAttempts field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetRetransmitAttempts(v int32) {
	o.RetransmitAttempts.Set(&v)
}
// SetRetransmitAttemptsNil sets the value for RetransmitAttempts to be an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetRetransmitAttemptsNil() {
	o.RetransmitAttempts.Set(nil)
}

// UnsetRetransmitAttempts ensures that no value is present for RetransmitAttempts, not even an explicit nil
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) UnsetRetransmitAttempts() {
	o.RetransmitAttempts.Unset()
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *LdapprofilesPutRequestLdapProfileValueLdapServersInner) SetIndex(v int32) {
	o.Index = &v
}

func (o LdapprofilesPutRequestLdapProfileValueLdapServersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LdapprofilesPutRequestLdapProfileValueLdapServersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Server) {
		toSerialize["server"] = o.Server
	}
	if o.Port.IsSet() {
		toSerialize["port"] = o.Port.Get()
	}
	if !IsNil(o.UseType) {
		toSerialize["use_type"] = o.UseType
	}
	if o.Priority.IsSet() {
		toSerialize["priority"] = o.Priority.Get()
	}
	if !IsNil(o.SslTlsMode) {
		toSerialize["ssl_tls_mode"] = o.SslTlsMode
	}
	if o.RetransmitAttempts.IsSet() {
		toSerialize["retransmit_attempts"] = o.RetransmitAttempts.Get()
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	return toSerialize, nil
}

type NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner struct {
	value *LdapprofilesPutRequestLdapProfileValueLdapServersInner
	isSet bool
}

func (v NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) Get() *LdapprofilesPutRequestLdapProfileValueLdapServersInner {
	return v.value
}

func (v *NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) Set(val *LdapprofilesPutRequestLdapProfileValueLdapServersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLdapprofilesPutRequestLdapProfileValueLdapServersInner(val *LdapprofilesPutRequestLdapProfileValueLdapServersInner) *NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner {
	return &NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner{value: val, isSet: true}
}

func (v NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLdapprofilesPutRequestLdapProfileValueLdapServersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


