/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner{}

// ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner struct for ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner
type ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner struct {
	// Enable this AS Path Access List
	Enable *bool `json:"enable,omitempty"`
	// Regular Expression to match BGP Community Strings
	RegularExpression *string `json:"regular_expression,omitempty"`
	// The index identifying the object. Zero if you want to add an object to the list.
	Index *int32 `json:"index,omitempty"`
}

// NewConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner instantiates a new ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner() *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner {
	this := ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner{}
	var enable bool = false
	this.Enable = &enable
	var regularExpression string = ""
	this.RegularExpression = &regularExpression
	return &this
}

// NewConfigPutRequestAsPathAccessListAsPathAccessListNameListsInnerWithDefaults instantiates a new ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestAsPathAccessListAsPathAccessListNameListsInnerWithDefaults() *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner {
	this := ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner{}
	var enable bool = false
	this.Enable = &enable
	var regularExpression string = ""
	this.RegularExpression = &regularExpression
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) SetEnable(v bool) {
	o.Enable = &v
}

// GetRegularExpression returns the RegularExpression field value if set, zero value otherwise.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetRegularExpression() string {
	if o == nil || IsNil(o.RegularExpression) {
		var ret string
		return ret
	}
	return *o.RegularExpression
}

// GetRegularExpressionOk returns a tuple with the RegularExpression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetRegularExpressionOk() (*string, bool) {
	if o == nil || IsNil(o.RegularExpression) {
		return nil, false
	}
	return o.RegularExpression, true
}

// HasRegularExpression returns a boolean if a field has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) HasRegularExpression() bool {
	if o != nil && !IsNil(o.RegularExpression) {
		return true
	}

	return false
}

// SetRegularExpression gets a reference to the given string and assigns it to the RegularExpression field.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) SetRegularExpression(v string) {
	o.RegularExpression = &v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) SetIndex(v int32) {
	o.Index = &v
}

func (o ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.RegularExpression) {
		toSerialize["regular_expression"] = o.RegularExpression
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	return toSerialize, nil
}

type NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner struct {
	value *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner
	isSet bool
}

func (v NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) Get() *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner {
	return v.value
}

func (v *NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) Set(val *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner(val *ConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) *NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner {
	return &NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner{value: val, isSet: true}
}

func (v NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestAsPathAccessListAsPathAccessListNameListsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


