/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestServicePortProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestServicePortProfile{}

// ConfigPutRequestServicePortProfile struct for ConfigPutRequestServicePortProfile
type ConfigPutRequestServicePortProfile struct {
	ServicePortProfileName *ConfigPutRequestServicePortProfileServicePortProfileName `json:"service_port_profile_name,omitempty"`
}

// NewConfigPutRequestServicePortProfile instantiates a new ConfigPutRequestServicePortProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestServicePortProfile() *ConfigPutRequestServicePortProfile {
	this := ConfigPutRequestServicePortProfile{}
	return &this
}

// NewConfigPutRequestServicePortProfileWithDefaults instantiates a new ConfigPutRequestServicePortProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestServicePortProfileWithDefaults() *ConfigPutRequestServicePortProfile {
	this := ConfigPutRequestServicePortProfile{}
	return &this
}

// GetServicePortProfileName returns the ServicePortProfileName field value if set, zero value otherwise.
func (o *ConfigPutRequestServicePortProfile) GetServicePortProfileName() ConfigPutRequestServicePortProfileServicePortProfileName {
	if o == nil || IsNil(o.ServicePortProfileName) {
		var ret ConfigPutRequestServicePortProfileServicePortProfileName
		return ret
	}
	return *o.ServicePortProfileName
}

// GetServicePortProfileNameOk returns a tuple with the ServicePortProfileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestServicePortProfile) GetServicePortProfileNameOk() (*ConfigPutRequestServicePortProfileServicePortProfileName, bool) {
	if o == nil || IsNil(o.ServicePortProfileName) {
		return nil, false
	}
	return o.ServicePortProfileName, true
}

// HasServicePortProfileName returns a boolean if a field has been set.
func (o *ConfigPutRequestServicePortProfile) HasServicePortProfileName() bool {
	if o != nil && !IsNil(o.ServicePortProfileName) {
		return true
	}

	return false
}

// SetServicePortProfileName gets a reference to the given ConfigPutRequestServicePortProfileServicePortProfileName and assigns it to the ServicePortProfileName field.
func (o *ConfigPutRequestServicePortProfile) SetServicePortProfileName(v ConfigPutRequestServicePortProfileServicePortProfileName) {
	o.ServicePortProfileName = &v
}

func (o ConfigPutRequestServicePortProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestServicePortProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServicePortProfileName) {
		toSerialize["service_port_profile_name"] = o.ServicePortProfileName
	}
	return toSerialize, nil
}

type NullableConfigPutRequestServicePortProfile struct {
	value *ConfigPutRequestServicePortProfile
	isSet bool
}

func (v NullableConfigPutRequestServicePortProfile) Get() *ConfigPutRequestServicePortProfile {
	return v.value
}

func (v *NullableConfigPutRequestServicePortProfile) Set(val *ConfigPutRequestServicePortProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestServicePortProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestServicePortProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestServicePortProfile(val *ConfigPutRequestServicePortProfile) *NullableConfigPutRequestServicePortProfile {
	return &NullableConfigPutRequestServicePortProfile{value: val, isSet: true}
}

func (v NullableConfigPutRequestServicePortProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestServicePortProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


