/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ThresholdgroupsPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThresholdgroupsPutRequest{}

// ThresholdgroupsPutRequest struct for ThresholdgroupsPutRequest
type ThresholdgroupsPutRequest struct {
	ThresholdGroup *map[string]ThresholdgroupsPutRequestThresholdGroupValue `json:"threshold_group,omitempty"`
}

// NewThresholdgroupsPutRequest instantiates a new ThresholdgroupsPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThresholdgroupsPutRequest() *ThresholdgroupsPutRequest {
	this := ThresholdgroupsPutRequest{}
	return &this
}

// NewThresholdgroupsPutRequestWithDefaults instantiates a new ThresholdgroupsPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThresholdgroupsPutRequestWithDefaults() *ThresholdgroupsPutRequest {
	this := ThresholdgroupsPutRequest{}
	return &this
}

// GetThresholdGroup returns the ThresholdGroup field value if set, zero value otherwise.
func (o *ThresholdgroupsPutRequest) GetThresholdGroup() map[string]ThresholdgroupsPutRequestThresholdGroupValue {
	if o == nil || IsNil(o.ThresholdGroup) {
		var ret map[string]ThresholdgroupsPutRequestThresholdGroupValue
		return ret
	}
	return *o.ThresholdGroup
}

// GetThresholdGroupOk returns a tuple with the ThresholdGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThresholdgroupsPutRequest) GetThresholdGroupOk() (*map[string]ThresholdgroupsPutRequestThresholdGroupValue, bool) {
	if o == nil || IsNil(o.ThresholdGroup) {
		return nil, false
	}
	return o.ThresholdGroup, true
}

// HasThresholdGroup returns a boolean if a field has been set.
func (o *ThresholdgroupsPutRequest) HasThresholdGroup() bool {
	if o != nil && !IsNil(o.ThresholdGroup) {
		return true
	}

	return false
}

// SetThresholdGroup gets a reference to the given map[string]ThresholdgroupsPutRequestThresholdGroupValue and assigns it to the ThresholdGroup field.
func (o *ThresholdgroupsPutRequest) SetThresholdGroup(v map[string]ThresholdgroupsPutRequestThresholdGroupValue) {
	o.ThresholdGroup = &v
}

func (o ThresholdgroupsPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThresholdgroupsPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ThresholdGroup) {
		toSerialize["threshold_group"] = o.ThresholdGroup
	}
	return toSerialize, nil
}

type NullableThresholdgroupsPutRequest struct {
	value *ThresholdgroupsPutRequest
	isSet bool
}

func (v NullableThresholdgroupsPutRequest) Get() *ThresholdgroupsPutRequest {
	return v.value
}

func (v *NullableThresholdgroupsPutRequest) Set(val *ThresholdgroupsPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableThresholdgroupsPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableThresholdgroupsPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThresholdgroupsPutRequest(val *ThresholdgroupsPutRequest) *NullableThresholdgroupsPutRequest {
	return &NullableThresholdgroupsPutRequest{value: val, isSet: true}
}

func (v NullableThresholdgroupsPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThresholdgroupsPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


