/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EthportprofilesPutRequestEthPortProfileValueObjectProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EthportprofilesPutRequestEthPortProfileValueObjectProperties{}

// EthportprofilesPutRequestEthPortProfileValueObjectProperties struct for EthportprofilesPutRequestEthPortProfileValueObjectProperties
type EthportprofilesPutRequestEthPortProfileValueObjectProperties struct {
	// Group
	Group *string `json:"group,omitempty"`
	// Defines importance of Link Down on this port
	PortMonitoring *string `json:"port_monitoring,omitempty"`
	// Choose to sort by service name or by order of creation
	SortByName *bool `json:"sort_by_name,omitempty"`
	// Port Label displayed ports provisioned with this Eth Port Profile but with no Port Label defined in the endpoint
	Label *string `json:"label,omitempty"`
	// Port Icon displayed ports provisioned with this Eth Port Profile but with no Port Icon defined in the endpoint
	Icon *string `json:"icon,omitempty"`
}

// NewEthportprofilesPutRequestEthPortProfileValueObjectProperties instantiates a new EthportprofilesPutRequestEthPortProfileValueObjectProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEthportprofilesPutRequestEthPortProfileValueObjectProperties() *EthportprofilesPutRequestEthPortProfileValueObjectProperties {
	this := EthportprofilesPutRequestEthPortProfileValueObjectProperties{}
	var group string = ""
	this.Group = &group
	var portMonitoring string = ""
	this.PortMonitoring = &portMonitoring
	var sortByName bool = false
	this.SortByName = &sortByName
	var label string = ""
	this.Label = &label
	var icon string = "empty"
	this.Icon = &icon
	return &this
}

// NewEthportprofilesPutRequestEthPortProfileValueObjectPropertiesWithDefaults instantiates a new EthportprofilesPutRequestEthPortProfileValueObjectProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEthportprofilesPutRequestEthPortProfileValueObjectPropertiesWithDefaults() *EthportprofilesPutRequestEthPortProfileValueObjectProperties {
	this := EthportprofilesPutRequestEthPortProfileValueObjectProperties{}
	var group string = ""
	this.Group = &group
	var portMonitoring string = ""
	this.PortMonitoring = &portMonitoring
	var sortByName bool = false
	this.SortByName = &sortByName
	var label string = ""
	this.Label = &label
	var icon string = "empty"
	this.Icon = &icon
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetGroup() string {
	if o == nil || IsNil(o.Group) {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetGroupOk() (*string, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) SetGroup(v string) {
	o.Group = &v
}

// GetPortMonitoring returns the PortMonitoring field value if set, zero value otherwise.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetPortMonitoring() string {
	if o == nil || IsNil(o.PortMonitoring) {
		var ret string
		return ret
	}
	return *o.PortMonitoring
}

// GetPortMonitoringOk returns a tuple with the PortMonitoring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetPortMonitoringOk() (*string, bool) {
	if o == nil || IsNil(o.PortMonitoring) {
		return nil, false
	}
	return o.PortMonitoring, true
}

// HasPortMonitoring returns a boolean if a field has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) HasPortMonitoring() bool {
	if o != nil && !IsNil(o.PortMonitoring) {
		return true
	}

	return false
}

// SetPortMonitoring gets a reference to the given string and assigns it to the PortMonitoring field.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) SetPortMonitoring(v string) {
	o.PortMonitoring = &v
}

// GetSortByName returns the SortByName field value if set, zero value otherwise.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetSortByName() bool {
	if o == nil || IsNil(o.SortByName) {
		var ret bool
		return ret
	}
	return *o.SortByName
}

// GetSortByNameOk returns a tuple with the SortByName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetSortByNameOk() (*bool, bool) {
	if o == nil || IsNil(o.SortByName) {
		return nil, false
	}
	return o.SortByName, true
}

// HasSortByName returns a boolean if a field has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) HasSortByName() bool {
	if o != nil && !IsNil(o.SortByName) {
		return true
	}

	return false
}

// SetSortByName gets a reference to the given bool and assigns it to the SortByName field.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) SetSortByName(v bool) {
	o.SortByName = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) SetLabel(v string) {
	o.Label = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *EthportprofilesPutRequestEthPortProfileValueObjectProperties) SetIcon(v string) {
	o.Icon = &v
}

func (o EthportprofilesPutRequestEthPortProfileValueObjectProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EthportprofilesPutRequestEthPortProfileValueObjectProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.PortMonitoring) {
		toSerialize["port_monitoring"] = o.PortMonitoring
	}
	if !IsNil(o.SortByName) {
		toSerialize["sort_by_name"] = o.SortByName
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	return toSerialize, nil
}

type NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties struct {
	value *EthportprofilesPutRequestEthPortProfileValueObjectProperties
	isSet bool
}

func (v NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) Get() *EthportprofilesPutRequestEthPortProfileValueObjectProperties {
	return v.value
}

func (v *NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) Set(val *EthportprofilesPutRequestEthPortProfileValueObjectProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEthportprofilesPutRequestEthPortProfileValueObjectProperties(val *EthportprofilesPutRequestEthPortProfileValueObjectProperties) *NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties {
	return &NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties{value: val, isSet: true}
}

func (v NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEthportprofilesPutRequestEthPortProfileValueObjectProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


