/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SusPutRequestSuValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SusPutRequestSuValue{}

// SusPutRequestSuValue struct for SusPutRequestSuValue
type SusPutRequestSuValue struct {
	// Template Name. Must be unique within type.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	// Pod this SU is assigned to
	Pod *string `json:"pod,omitempty"`
	// Object type for pod field
	PodRefType *string `json:"pod_ref_type_,omitempty"`
	// Position of the Switch
	Position NullableFloat32 `json:"position,omitempty"`
	ObjectProperties *AclsPutRequestIpFilterValueObjectProperties `json:"object_properties,omitempty"`
}

// NewSusPutRequestSuValue instantiates a new SusPutRequestSuValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSusPutRequestSuValue() *SusPutRequestSuValue {
	this := SusPutRequestSuValue{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var pod string = ""
	this.Pod = &pod
	return &this
}

// NewSusPutRequestSuValueWithDefaults instantiates a new SusPutRequestSuValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSusPutRequestSuValueWithDefaults() *SusPutRequestSuValue {
	this := SusPutRequestSuValue{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var pod string = ""
	this.Pod = &pod
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SusPutRequestSuValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SusPutRequestSuValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SusPutRequestSuValue) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *SusPutRequestSuValue) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SusPutRequestSuValue) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *SusPutRequestSuValue) SetEnable(v bool) {
	o.Enable = &v
}

// GetPod returns the Pod field value if set, zero value otherwise.
func (o *SusPutRequestSuValue) GetPod() string {
	if o == nil || IsNil(o.Pod) {
		var ret string
		return ret
	}
	return *o.Pod
}

// GetPodOk returns a tuple with the Pod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SusPutRequestSuValue) GetPodOk() (*string, bool) {
	if o == nil || IsNil(o.Pod) {
		return nil, false
	}
	return o.Pod, true
}

// HasPod returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasPod() bool {
	if o != nil && !IsNil(o.Pod) {
		return true
	}

	return false
}

// SetPod gets a reference to the given string and assigns it to the Pod field.
func (o *SusPutRequestSuValue) SetPod(v string) {
	o.Pod = &v
}

// GetPodRefType returns the PodRefType field value if set, zero value otherwise.
func (o *SusPutRequestSuValue) GetPodRefType() string {
	if o == nil || IsNil(o.PodRefType) {
		var ret string
		return ret
	}
	return *o.PodRefType
}

// GetPodRefTypeOk returns a tuple with the PodRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SusPutRequestSuValue) GetPodRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PodRefType) {
		return nil, false
	}
	return o.PodRefType, true
}

// HasPodRefType returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasPodRefType() bool {
	if o != nil && !IsNil(o.PodRefType) {
		return true
	}

	return false
}

// SetPodRefType gets a reference to the given string and assigns it to the PodRefType field.
func (o *SusPutRequestSuValue) SetPodRefType(v string) {
	o.PodRefType = &v
}

// GetPosition returns the Position field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SusPutRequestSuValue) GetPosition() float32 {
	if o == nil || IsNil(o.Position.Get()) {
		var ret float32
		return ret
	}
	return *o.Position.Get()
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SusPutRequestSuValue) GetPositionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Position.Get(), o.Position.IsSet()
}

// HasPosition returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasPosition() bool {
	if o != nil && o.Position.IsSet() {
		return true
	}

	return false
}

// SetPosition gets a reference to the given NullableFloat32 and assigns it to the Position field.
func (o *SusPutRequestSuValue) SetPosition(v float32) {
	o.Position.Set(&v)
}
// SetPositionNil sets the value for Position to be an explicit nil
func (o *SusPutRequestSuValue) SetPositionNil() {
	o.Position.Set(nil)
}

// UnsetPosition ensures that no value is present for Position, not even an explicit nil
func (o *SusPutRequestSuValue) UnsetPosition() {
	o.Position.Unset()
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *SusPutRequestSuValue) GetObjectProperties() AclsPutRequestIpFilterValueObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret AclsPutRequestIpFilterValueObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SusPutRequestSuValue) GetObjectPropertiesOk() (*AclsPutRequestIpFilterValueObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *SusPutRequestSuValue) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given AclsPutRequestIpFilterValueObjectProperties and assigns it to the ObjectProperties field.
func (o *SusPutRequestSuValue) SetObjectProperties(v AclsPutRequestIpFilterValueObjectProperties) {
	o.ObjectProperties = &v
}

func (o SusPutRequestSuValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SusPutRequestSuValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Pod) {
		toSerialize["pod"] = o.Pod
	}
	if !IsNil(o.PodRefType) {
		toSerialize["pod_ref_type_"] = o.PodRefType
	}
	if o.Position.IsSet() {
		toSerialize["position"] = o.Position.Get()
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableSusPutRequestSuValue struct {
	value *SusPutRequestSuValue
	isSet bool
}

func (v NullableSusPutRequestSuValue) Get() *SusPutRequestSuValue {
	return v.value
}

func (v *NullableSusPutRequestSuValue) Set(val *SusPutRequestSuValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSusPutRequestSuValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSusPutRequestSuValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSusPutRequestSuValue(val *SusPutRequestSuValue) *NullableSusPutRequestSuValue {
	return &NullableSusPutRequestSuValue{value: val, isSet: true}
}

func (v NullableSusPutRequestSuValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSusPutRequestSuValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


