/*
Manager system API

This application demonstrates the usage of Manager system API.

API version: 6.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MonitoringaclsPutRequestMonitoringAclValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MonitoringaclsPutRequestMonitoringAclValue{}

// MonitoringaclsPutRequestMonitoringAclValue struct for MonitoringaclsPutRequestMonitoringAclValue
type MonitoringaclsPutRequestMonitoringAclValue struct {
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	// Template Name. Must be unique within type.
	Name     *string                                                   `json:"name,omitempty"`
	Services []MonitoringaclsPutRequestMonitoringAclValueServicesInner `json:"services,omitempty"`
}

// NewMonitoringaclsPutRequestMonitoringAclValue instantiates a new MonitoringaclsPutRequestMonitoringAclValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMonitoringaclsPutRequestMonitoringAclValue() *MonitoringaclsPutRequestMonitoringAclValue {
	this := MonitoringaclsPutRequestMonitoringAclValue{}
	var enable bool = false
	this.Enable = &enable
	var name string = ""
	this.Name = &name
	return &this
}

// NewMonitoringaclsPutRequestMonitoringAclValueWithDefaults instantiates a new MonitoringaclsPutRequestMonitoringAclValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMonitoringaclsPutRequestMonitoringAclValueWithDefaults() *MonitoringaclsPutRequestMonitoringAclValue {
	this := MonitoringaclsPutRequestMonitoringAclValue{}
	var enable bool = false
	this.Enable = &enable
	var name string = ""
	this.Name = &name
	return &this
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *MonitoringaclsPutRequestMonitoringAclValue) SetEnable(v bool) {
	o.Enable = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MonitoringaclsPutRequestMonitoringAclValue) SetName(v string) {
	o.Name = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetServices() []MonitoringaclsPutRequestMonitoringAclValueServicesInner {
	if o == nil || IsNil(o.Services) {
		var ret []MonitoringaclsPutRequestMonitoringAclValueServicesInner
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) GetServicesOk() ([]MonitoringaclsPutRequestMonitoringAclValueServicesInner, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *MonitoringaclsPutRequestMonitoringAclValue) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []MonitoringaclsPutRequestMonitoringAclValueServicesInner and assigns it to the Services field.
func (o *MonitoringaclsPutRequestMonitoringAclValue) SetServices(v []MonitoringaclsPutRequestMonitoringAclValueServicesInner) {
	o.Services = v
}

func (o MonitoringaclsPutRequestMonitoringAclValue) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MonitoringaclsPutRequestMonitoringAclValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableMonitoringaclsPutRequestMonitoringAclValue struct {
	value *MonitoringaclsPutRequestMonitoringAclValue
	isSet bool
}

func (v NullableMonitoringaclsPutRequestMonitoringAclValue) Get() *MonitoringaclsPutRequestMonitoringAclValue {
	return v.value
}

func (v *NullableMonitoringaclsPutRequestMonitoringAclValue) Set(val *MonitoringaclsPutRequestMonitoringAclValue) {
	v.value = val
	v.isSet = true
}

func (v NullableMonitoringaclsPutRequestMonitoringAclValue) IsSet() bool {
	return v.isSet
}

func (v *NullableMonitoringaclsPutRequestMonitoringAclValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMonitoringaclsPutRequestMonitoringAclValue(val *MonitoringaclsPutRequestMonitoringAclValue) *NullableMonitoringaclsPutRequestMonitoringAclValue {
	return &NullableMonitoringaclsPutRequestMonitoringAclValue{value: val, isSet: true}
}

func (v NullableMonitoringaclsPutRequestMonitoringAclValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMonitoringaclsPutRequestMonitoringAclValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
