/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestSfpBreakoutsSfpBreakoutsName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestSfpBreakoutsSfpBreakoutsName{}

// ConfigPutRequestSfpBreakoutsSfpBreakoutsName struct for ConfigPutRequestSfpBreakoutsSfpBreakoutsName
type ConfigPutRequestSfpBreakoutsSfpBreakoutsName struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	Breakout []ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner `json:"breakout,omitempty"`
	ObjectProperties map[string]interface{} `json:"object_properties,omitempty"`
}

// NewConfigPutRequestSfpBreakoutsSfpBreakoutsName instantiates a new ConfigPutRequestSfpBreakoutsSfpBreakoutsName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestSfpBreakoutsSfpBreakoutsName() *ConfigPutRequestSfpBreakoutsSfpBreakoutsName {
	this := ConfigPutRequestSfpBreakoutsSfpBreakoutsName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// NewConfigPutRequestSfpBreakoutsSfpBreakoutsNameWithDefaults instantiates a new ConfigPutRequestSfpBreakoutsSfpBreakoutsName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestSfpBreakoutsSfpBreakoutsNameWithDefaults() *ConfigPutRequestSfpBreakoutsSfpBreakoutsName {
	this := ConfigPutRequestSfpBreakoutsSfpBreakoutsName{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) SetEnable(v bool) {
	o.Enable = &v
}

// GetBreakout returns the Breakout field value if set, zero value otherwise.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetBreakout() []ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner {
	if o == nil || IsNil(o.Breakout) {
		var ret []ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner
		return ret
	}
	return o.Breakout
}

// GetBreakoutOk returns a tuple with the Breakout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetBreakoutOk() ([]ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner, bool) {
	if o == nil || IsNil(o.Breakout) {
		return nil, false
	}
	return o.Breakout, true
}

// HasBreakout returns a boolean if a field has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) HasBreakout() bool {
	if o != nil && !IsNil(o.Breakout) {
		return true
	}

	return false
}

// SetBreakout gets a reference to the given []ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner and assigns it to the Breakout field.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) SetBreakout(v []ConfigPutRequestSfpBreakoutsSfpBreakoutsNameBreakoutInner) {
	o.Breakout = v
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetObjectProperties() map[string]interface{} {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret map[string]interface{}
		return ret
	}
	return o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) GetObjectPropertiesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return map[string]interface{}{}, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given map[string]interface{} and assigns it to the ObjectProperties field.
func (o *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) SetObjectProperties(v map[string]interface{}) {
	o.ObjectProperties = v
}

func (o ConfigPutRequestSfpBreakoutsSfpBreakoutsName) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestSfpBreakoutsSfpBreakoutsName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Breakout) {
		toSerialize["breakout"] = o.Breakout
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName struct {
	value *ConfigPutRequestSfpBreakoutsSfpBreakoutsName
	isSet bool
}

func (v NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) Get() *ConfigPutRequestSfpBreakoutsSfpBreakoutsName {
	return v.value
}

func (v *NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) Set(val *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestSfpBreakoutsSfpBreakoutsName(val *ConfigPutRequestSfpBreakoutsSfpBreakoutsName) *NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName {
	return &NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName{value: val, isSet: true}
}

func (v NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestSfpBreakoutsSfpBreakoutsName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


