/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PacketbrokerPutRequestPortAclValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PacketbrokerPutRequestPortAclValue{}

// PacketbrokerPutRequestPortAclValue struct for PacketbrokerPutRequestPortAclValue
type PacketbrokerPutRequestPortAclValue struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	Ipv4Permit []PacketbrokerPutRequestPortAclValueIpv4PermitInner `json:"ipv4_permit,omitempty"`
	Ipv4Deny []PacketbrokerPutRequestPortAclValueIpv4PermitInner `json:"ipv4_deny,omitempty"`
	Ipv6Permit []PacketbrokerPutRequestPortAclValueIpv6PermitInner `json:"ipv6_permit,omitempty"`
	Ipv6Deny []PacketbrokerPutRequestPortAclValueIpv6PermitInner `json:"ipv6_deny,omitempty"`
}

// NewPacketbrokerPutRequestPortAclValue instantiates a new PacketbrokerPutRequestPortAclValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPacketbrokerPutRequestPortAclValue() *PacketbrokerPutRequestPortAclValue {
	this := PacketbrokerPutRequestPortAclValue{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// NewPacketbrokerPutRequestPortAclValueWithDefaults instantiates a new PacketbrokerPutRequestPortAclValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPacketbrokerPutRequestPortAclValueWithDefaults() *PacketbrokerPutRequestPortAclValue {
	this := PacketbrokerPutRequestPortAclValue{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PacketbrokerPutRequestPortAclValue) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *PacketbrokerPutRequestPortAclValue) SetEnable(v bool) {
	o.Enable = &v
}

// GetIpv4Permit returns the Ipv4Permit field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv4Permit() []PacketbrokerPutRequestPortAclValueIpv4PermitInner {
	if o == nil || IsNil(o.Ipv4Permit) {
		var ret []PacketbrokerPutRequestPortAclValueIpv4PermitInner
		return ret
	}
	return o.Ipv4Permit
}

// GetIpv4PermitOk returns a tuple with the Ipv4Permit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv4PermitOk() ([]PacketbrokerPutRequestPortAclValueIpv4PermitInner, bool) {
	if o == nil || IsNil(o.Ipv4Permit) {
		return nil, false
	}
	return o.Ipv4Permit, true
}

// HasIpv4Permit returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasIpv4Permit() bool {
	if o != nil && !IsNil(o.Ipv4Permit) {
		return true
	}

	return false
}

// SetIpv4Permit gets a reference to the given []PacketbrokerPutRequestPortAclValueIpv4PermitInner and assigns it to the Ipv4Permit field.
func (o *PacketbrokerPutRequestPortAclValue) SetIpv4Permit(v []PacketbrokerPutRequestPortAclValueIpv4PermitInner) {
	o.Ipv4Permit = v
}

// GetIpv4Deny returns the Ipv4Deny field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv4Deny() []PacketbrokerPutRequestPortAclValueIpv4PermitInner {
	if o == nil || IsNil(o.Ipv4Deny) {
		var ret []PacketbrokerPutRequestPortAclValueIpv4PermitInner
		return ret
	}
	return o.Ipv4Deny
}

// GetIpv4DenyOk returns a tuple with the Ipv4Deny field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv4DenyOk() ([]PacketbrokerPutRequestPortAclValueIpv4PermitInner, bool) {
	if o == nil || IsNil(o.Ipv4Deny) {
		return nil, false
	}
	return o.Ipv4Deny, true
}

// HasIpv4Deny returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasIpv4Deny() bool {
	if o != nil && !IsNil(o.Ipv4Deny) {
		return true
	}

	return false
}

// SetIpv4Deny gets a reference to the given []PacketbrokerPutRequestPortAclValueIpv4PermitInner and assigns it to the Ipv4Deny field.
func (o *PacketbrokerPutRequestPortAclValue) SetIpv4Deny(v []PacketbrokerPutRequestPortAclValueIpv4PermitInner) {
	o.Ipv4Deny = v
}

// GetIpv6Permit returns the Ipv6Permit field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv6Permit() []PacketbrokerPutRequestPortAclValueIpv6PermitInner {
	if o == nil || IsNil(o.Ipv6Permit) {
		var ret []PacketbrokerPutRequestPortAclValueIpv6PermitInner
		return ret
	}
	return o.Ipv6Permit
}

// GetIpv6PermitOk returns a tuple with the Ipv6Permit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv6PermitOk() ([]PacketbrokerPutRequestPortAclValueIpv6PermitInner, bool) {
	if o == nil || IsNil(o.Ipv6Permit) {
		return nil, false
	}
	return o.Ipv6Permit, true
}

// HasIpv6Permit returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasIpv6Permit() bool {
	if o != nil && !IsNil(o.Ipv6Permit) {
		return true
	}

	return false
}

// SetIpv6Permit gets a reference to the given []PacketbrokerPutRequestPortAclValueIpv6PermitInner and assigns it to the Ipv6Permit field.
func (o *PacketbrokerPutRequestPortAclValue) SetIpv6Permit(v []PacketbrokerPutRequestPortAclValueIpv6PermitInner) {
	o.Ipv6Permit = v
}

// GetIpv6Deny returns the Ipv6Deny field value if set, zero value otherwise.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv6Deny() []PacketbrokerPutRequestPortAclValueIpv6PermitInner {
	if o == nil || IsNil(o.Ipv6Deny) {
		var ret []PacketbrokerPutRequestPortAclValueIpv6PermitInner
		return ret
	}
	return o.Ipv6Deny
}

// GetIpv6DenyOk returns a tuple with the Ipv6Deny field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PacketbrokerPutRequestPortAclValue) GetIpv6DenyOk() ([]PacketbrokerPutRequestPortAclValueIpv6PermitInner, bool) {
	if o == nil || IsNil(o.Ipv6Deny) {
		return nil, false
	}
	return o.Ipv6Deny, true
}

// HasIpv6Deny returns a boolean if a field has been set.
func (o *PacketbrokerPutRequestPortAclValue) HasIpv6Deny() bool {
	if o != nil && !IsNil(o.Ipv6Deny) {
		return true
	}

	return false
}

// SetIpv6Deny gets a reference to the given []PacketbrokerPutRequestPortAclValueIpv6PermitInner and assigns it to the Ipv6Deny field.
func (o *PacketbrokerPutRequestPortAclValue) SetIpv6Deny(v []PacketbrokerPutRequestPortAclValueIpv6PermitInner) {
	o.Ipv6Deny = v
}

func (o PacketbrokerPutRequestPortAclValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PacketbrokerPutRequestPortAclValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.Ipv4Permit) {
		toSerialize["ipv4_permit"] = o.Ipv4Permit
	}
	if !IsNil(o.Ipv4Deny) {
		toSerialize["ipv4_deny"] = o.Ipv4Deny
	}
	if !IsNil(o.Ipv6Permit) {
		toSerialize["ipv6_permit"] = o.Ipv6Permit
	}
	if !IsNil(o.Ipv6Deny) {
		toSerialize["ipv6_deny"] = o.Ipv6Deny
	}
	return toSerialize, nil
}

type NullablePacketbrokerPutRequestPortAclValue struct {
	value *PacketbrokerPutRequestPortAclValue
	isSet bool
}

func (v NullablePacketbrokerPutRequestPortAclValue) Get() *PacketbrokerPutRequestPortAclValue {
	return v.value
}

func (v *NullablePacketbrokerPutRequestPortAclValue) Set(val *PacketbrokerPutRequestPortAclValue) {
	v.value = val
	v.isSet = true
}

func (v NullablePacketbrokerPutRequestPortAclValue) IsSet() bool {
	return v.isSet
}

func (v *NullablePacketbrokerPutRequestPortAclValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePacketbrokerPutRequestPortAclValue(val *PacketbrokerPutRequestPortAclValue) *NullablePacketbrokerPutRequestPortAclValue {
	return &NullablePacketbrokerPutRequestPortAclValue{value: val, isSet: true}
}

func (v NullablePacketbrokerPutRequestPortAclValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePacketbrokerPutRequestPortAclValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


