/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PolicybasedroutingPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicybasedroutingPutRequest{}

// PolicybasedroutingPutRequest struct for PolicybasedroutingPutRequest
type PolicybasedroutingPutRequest struct {
	PbRouting *map[string]PolicybasedroutingPutRequestPbRoutingValue `json:"pb_routing,omitempty"`
}

// NewPolicybasedroutingPutRequest instantiates a new PolicybasedroutingPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicybasedroutingPutRequest() *PolicybasedroutingPutRequest {
	this := PolicybasedroutingPutRequest{}
	return &this
}

// NewPolicybasedroutingPutRequestWithDefaults instantiates a new PolicybasedroutingPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicybasedroutingPutRequestWithDefaults() *PolicybasedroutingPutRequest {
	this := PolicybasedroutingPutRequest{}
	return &this
}

// GetPbRouting returns the PbRouting field value if set, zero value otherwise.
func (o *PolicybasedroutingPutRequest) GetPbRouting() map[string]PolicybasedroutingPutRequestPbRoutingValue {
	if o == nil || IsNil(o.PbRouting) {
		var ret map[string]PolicybasedroutingPutRequestPbRoutingValue
		return ret
	}
	return *o.PbRouting
}

// GetPbRoutingOk returns a tuple with the PbRouting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PolicybasedroutingPutRequest) GetPbRoutingOk() (*map[string]PolicybasedroutingPutRequestPbRoutingValue, bool) {
	if o == nil || IsNil(o.PbRouting) {
		return nil, false
	}
	return o.PbRouting, true
}

// HasPbRouting returns a boolean if a field has been set.
func (o *PolicybasedroutingPutRequest) HasPbRouting() bool {
	if o != nil && !IsNil(o.PbRouting) {
		return true
	}

	return false
}

// SetPbRouting gets a reference to the given map[string]PolicybasedroutingPutRequestPbRoutingValue and assigns it to the PbRouting field.
func (o *PolicybasedroutingPutRequest) SetPbRouting(v map[string]PolicybasedroutingPutRequestPbRoutingValue) {
	o.PbRouting = &v
}

func (o PolicybasedroutingPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicybasedroutingPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PbRouting) {
		toSerialize["pb_routing"] = o.PbRouting
	}
	return toSerialize, nil
}

type NullablePolicybasedroutingPutRequest struct {
	value *PolicybasedroutingPutRequest
	isSet bool
}

func (v NullablePolicybasedroutingPutRequest) Get() *PolicybasedroutingPutRequest {
	return v.value
}

func (v *NullablePolicybasedroutingPutRequest) Set(val *PolicybasedroutingPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicybasedroutingPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicybasedroutingPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicybasedroutingPutRequest(val *PolicybasedroutingPutRequest) *NullablePolicybasedroutingPutRequest {
	return &NullablePolicybasedroutingPutRequest{value: val, isSet: true}
}

func (v NullablePolicybasedroutingPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicybasedroutingPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


