/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceportprofilesPutRequestServicePortProfileValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceportprofilesPutRequestServicePortProfileValue{}

// ServiceportprofilesPutRequestServicePortProfileValue struct for ServiceportprofilesPutRequestServicePortProfileValue
type ServiceportprofilesPutRequestServicePortProfileValue struct {
	// Object Name. Must be unique.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	// Determines what Service are provisioned on the port and if those Services are propagated upstream<ul><li>* \"Upstream Switchport\" Services specified below.  Services are not propagated.</li><li>* \"Downstream Switchport\" Services specified below. Services are propagated.</li><li>* \"Crosslink Switchport\" Services is union of all Services on each switch.  Services are not propagated.</li><li>* \"Upstream L3 (L2/L3 Switches Only\" No Services.</li></ul>
	PortType *string `json:"port_type,omitempty"`
	// Speed of ingress (Mbps) for TLS (Transparent LAN Service)
	TlsLimitIn NullableInt32 `json:"tls_limit_in,omitempty"`
	// Service used for TLS (Transparent LAN Service)
	TlsService *string `json:"tls_service,omitempty"`
	// Object type for tls_service field
	TlsServiceRefType *string `json:"tls_service_ref_type_,omitempty"`
	// Trusted Ports do not participate in IP Source Guard, Dynamic ARP Inspection, nor DHCP Snooping, meaning all packets are forwarded without any checks.
	TrustedPort *bool `json:"trusted_port,omitempty"`
	// IP/Mask
	IpMask *string `json:"ip_mask,omitempty"`
	Services []ServiceportprofilesPutRequestServicePortProfileValueServicesInner `json:"services,omitempty"`
	ObjectProperties *ServiceportprofilesPutRequestServicePortProfileValueObjectProperties `json:"object_properties,omitempty"`
}

// NewServiceportprofilesPutRequestServicePortProfileValue instantiates a new ServiceportprofilesPutRequestServicePortProfileValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceportprofilesPutRequestServicePortProfileValue() *ServiceportprofilesPutRequestServicePortProfileValue {
	this := ServiceportprofilesPutRequestServicePortProfileValue{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	var portType string = "up"
	this.PortType = &portType
	var tlsLimitIn int32 = 1000
	this.TlsLimitIn = *NewNullableInt32(&tlsLimitIn)
	var tlsService string = ""
	this.TlsService = &tlsService
	var trustedPort bool = false
	this.TrustedPort = &trustedPort
	var ipMask string = ""
	this.IpMask = &ipMask
	return &this
}

// NewServiceportprofilesPutRequestServicePortProfileValueWithDefaults instantiates a new ServiceportprofilesPutRequestServicePortProfileValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceportprofilesPutRequestServicePortProfileValueWithDefaults() *ServiceportprofilesPutRequestServicePortProfileValue {
	this := ServiceportprofilesPutRequestServicePortProfileValue{}
	var name string = ""
	this.Name = &name
	var enable bool = false
	this.Enable = &enable
	var portType string = "up"
	this.PortType = &portType
	var tlsLimitIn int32 = 1000
	this.TlsLimitIn = *NewNullableInt32(&tlsLimitIn)
	var tlsService string = ""
	this.TlsService = &tlsService
	var trustedPort bool = false
	this.TrustedPort = &trustedPort
	var ipMask string = ""
	this.IpMask = &ipMask
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetEnable(v bool) {
	o.Enable = &v
}

// GetPortType returns the PortType field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetPortType() string {
	if o == nil || IsNil(o.PortType) {
		var ret string
		return ret
	}
	return *o.PortType
}

// GetPortTypeOk returns a tuple with the PortType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetPortTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PortType) {
		return nil, false
	}
	return o.PortType, true
}

// HasPortType returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasPortType() bool {
	if o != nil && !IsNil(o.PortType) {
		return true
	}

	return false
}

// SetPortType gets a reference to the given string and assigns it to the PortType field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetPortType(v string) {
	o.PortType = &v
}

// GetTlsLimitIn returns the TlsLimitIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsLimitIn() int32 {
	if o == nil || IsNil(o.TlsLimitIn.Get()) {
		var ret int32
		return ret
	}
	return *o.TlsLimitIn.Get()
}

// GetTlsLimitInOk returns a tuple with the TlsLimitIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsLimitInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TlsLimitIn.Get(), o.TlsLimitIn.IsSet()
}

// HasTlsLimitIn returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasTlsLimitIn() bool {
	if o != nil && o.TlsLimitIn.IsSet() {
		return true
	}

	return false
}

// SetTlsLimitIn gets a reference to the given NullableInt32 and assigns it to the TlsLimitIn field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetTlsLimitIn(v int32) {
	o.TlsLimitIn.Set(&v)
}
// SetTlsLimitInNil sets the value for TlsLimitIn to be an explicit nil
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetTlsLimitInNil() {
	o.TlsLimitIn.Set(nil)
}

// UnsetTlsLimitIn ensures that no value is present for TlsLimitIn, not even an explicit nil
func (o *ServiceportprofilesPutRequestServicePortProfileValue) UnsetTlsLimitIn() {
	o.TlsLimitIn.Unset()
}

// GetTlsService returns the TlsService field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsService() string {
	if o == nil || IsNil(o.TlsService) {
		var ret string
		return ret
	}
	return *o.TlsService
}

// GetTlsServiceOk returns a tuple with the TlsService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsServiceOk() (*string, bool) {
	if o == nil || IsNil(o.TlsService) {
		return nil, false
	}
	return o.TlsService, true
}

// HasTlsService returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasTlsService() bool {
	if o != nil && !IsNil(o.TlsService) {
		return true
	}

	return false
}

// SetTlsService gets a reference to the given string and assigns it to the TlsService field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetTlsService(v string) {
	o.TlsService = &v
}

// GetTlsServiceRefType returns the TlsServiceRefType field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsServiceRefType() string {
	if o == nil || IsNil(o.TlsServiceRefType) {
		var ret string
		return ret
	}
	return *o.TlsServiceRefType
}

// GetTlsServiceRefTypeOk returns a tuple with the TlsServiceRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTlsServiceRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.TlsServiceRefType) {
		return nil, false
	}
	return o.TlsServiceRefType, true
}

// HasTlsServiceRefType returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasTlsServiceRefType() bool {
	if o != nil && !IsNil(o.TlsServiceRefType) {
		return true
	}

	return false
}

// SetTlsServiceRefType gets a reference to the given string and assigns it to the TlsServiceRefType field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetTlsServiceRefType(v string) {
	o.TlsServiceRefType = &v
}

// GetTrustedPort returns the TrustedPort field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTrustedPort() bool {
	if o == nil || IsNil(o.TrustedPort) {
		var ret bool
		return ret
	}
	return *o.TrustedPort
}

// GetTrustedPortOk returns a tuple with the TrustedPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetTrustedPortOk() (*bool, bool) {
	if o == nil || IsNil(o.TrustedPort) {
		return nil, false
	}
	return o.TrustedPort, true
}

// HasTrustedPort returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasTrustedPort() bool {
	if o != nil && !IsNil(o.TrustedPort) {
		return true
	}

	return false
}

// SetTrustedPort gets a reference to the given bool and assigns it to the TrustedPort field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetTrustedPort(v bool) {
	o.TrustedPort = &v
}

// GetIpMask returns the IpMask field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetIpMask() string {
	if o == nil || IsNil(o.IpMask) {
		var ret string
		return ret
	}
	return *o.IpMask
}

// GetIpMaskOk returns a tuple with the IpMask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetIpMaskOk() (*string, bool) {
	if o == nil || IsNil(o.IpMask) {
		return nil, false
	}
	return o.IpMask, true
}

// HasIpMask returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasIpMask() bool {
	if o != nil && !IsNil(o.IpMask) {
		return true
	}

	return false
}

// SetIpMask gets a reference to the given string and assigns it to the IpMask field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetIpMask(v string) {
	o.IpMask = &v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetServices() []ServiceportprofilesPutRequestServicePortProfileValueServicesInner {
	if o == nil || IsNil(o.Services) {
		var ret []ServiceportprofilesPutRequestServicePortProfileValueServicesInner
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetServicesOk() ([]ServiceportprofilesPutRequestServicePortProfileValueServicesInner, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []ServiceportprofilesPutRequestServicePortProfileValueServicesInner and assigns it to the Services field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetServices(v []ServiceportprofilesPutRequestServicePortProfileValueServicesInner) {
	o.Services = v
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetObjectProperties() ServiceportprofilesPutRequestServicePortProfileValueObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret ServiceportprofilesPutRequestServicePortProfileValueObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) GetObjectPropertiesOk() (*ServiceportprofilesPutRequestServicePortProfileValueObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given ServiceportprofilesPutRequestServicePortProfileValueObjectProperties and assigns it to the ObjectProperties field.
func (o *ServiceportprofilesPutRequestServicePortProfileValue) SetObjectProperties(v ServiceportprofilesPutRequestServicePortProfileValueObjectProperties) {
	o.ObjectProperties = &v
}

func (o ServiceportprofilesPutRequestServicePortProfileValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceportprofilesPutRequestServicePortProfileValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.PortType) {
		toSerialize["port_type"] = o.PortType
	}
	if o.TlsLimitIn.IsSet() {
		toSerialize["tls_limit_in"] = o.TlsLimitIn.Get()
	}
	if !IsNil(o.TlsService) {
		toSerialize["tls_service"] = o.TlsService
	}
	if !IsNil(o.TlsServiceRefType) {
		toSerialize["tls_service_ref_type_"] = o.TlsServiceRefType
	}
	if !IsNil(o.TrustedPort) {
		toSerialize["trusted_port"] = o.TrustedPort
	}
	if !IsNil(o.IpMask) {
		toSerialize["ip_mask"] = o.IpMask
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullableServiceportprofilesPutRequestServicePortProfileValue struct {
	value *ServiceportprofilesPutRequestServicePortProfileValue
	isSet bool
}

func (v NullableServiceportprofilesPutRequestServicePortProfileValue) Get() *ServiceportprofilesPutRequestServicePortProfileValue {
	return v.value
}

func (v *NullableServiceportprofilesPutRequestServicePortProfileValue) Set(val *ServiceportprofilesPutRequestServicePortProfileValue) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceportprofilesPutRequestServicePortProfileValue) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceportprofilesPutRequestServicePortProfileValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceportprofilesPutRequestServicePortProfileValue(val *ServiceportprofilesPutRequestServicePortProfileValue) *NullableServiceportprofilesPutRequestServicePortProfileValue {
	return &NullableServiceportprofilesPutRequestServicePortProfileValue{value: val, isSet: true}
}

func (v NullableServiceportprofilesPutRequestServicePortProfileValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceportprofilesPutRequestServicePortProfileValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


