/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 6.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PodsPutRequestPodValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PodsPutRequestPodValue{}

// PodsPutRequestPodValue struct for PodsPutRequestPodValue
type PodsPutRequestPodValue struct {
	// Template Name. Must be unique within type.
	Name *string `json:"name,omitempty"`
	// Enable object.
	Enable *bool `json:"enable,omitempty"`
	// Number of spine switches expected in this pod
	ExpectedSpineCount NullableInt64 `json:"expected_spine_count,omitempty"`
	// Fabric this Pod is assigned to
	Fabric *string `json:"fabric,omitempty"`
	// Object type for fabric field
	FabricRefType *string `json:"fabric_ref_type_,omitempty"`
	// Position of the Switch
	Position NullableFloat64 `json:"position,omitempty"`
	ObjectProperties *AclsPutRequestIpFilterValueObjectProperties `json:"object_properties,omitempty"`
}

// NewPodsPutRequestPodValue instantiates a new PodsPutRequestPodValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPodsPutRequestPodValue() *PodsPutRequestPodValue {
	this := PodsPutRequestPodValue{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var expectedSpineCount int64 = 1
	this.ExpectedSpineCount = *NewNullableInt64(&expectedSpineCount)
	var fabric string = ""
	this.Fabric = &fabric
	return &this
}

// NewPodsPutRequestPodValueWithDefaults instantiates a new PodsPutRequestPodValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPodsPutRequestPodValueWithDefaults() *PodsPutRequestPodValue {
	this := PodsPutRequestPodValue{}
	var name string = ""
	this.Name = &name
	var enable bool = true
	this.Enable = &enable
	var expectedSpineCount int64 = 1
	this.ExpectedSpineCount = *NewNullableInt64(&expectedSpineCount)
	var fabric string = ""
	this.Fabric = &fabric
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PodsPutRequestPodValue) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodsPutRequestPodValue) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PodsPutRequestPodValue) SetName(v string) {
	o.Name = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *PodsPutRequestPodValue) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodsPutRequestPodValue) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *PodsPutRequestPodValue) SetEnable(v bool) {
	o.Enable = &v
}

// GetExpectedSpineCount returns the ExpectedSpineCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodsPutRequestPodValue) GetExpectedSpineCount() int64 {
	if o == nil || IsNil(o.ExpectedSpineCount.Get()) {
		var ret int64
		return ret
	}
	return *o.ExpectedSpineCount.Get()
}

// GetExpectedSpineCountOk returns a tuple with the ExpectedSpineCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodsPutRequestPodValue) GetExpectedSpineCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpectedSpineCount.Get(), o.ExpectedSpineCount.IsSet()
}

// HasExpectedSpineCount returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasExpectedSpineCount() bool {
	if o != nil && o.ExpectedSpineCount.IsSet() {
		return true
	}

	return false
}

// SetExpectedSpineCount gets a reference to the given NullableInt64 and assigns it to the ExpectedSpineCount field.
func (o *PodsPutRequestPodValue) SetExpectedSpineCount(v int64) {
	o.ExpectedSpineCount.Set(&v)
}
// SetExpectedSpineCountNil sets the value for ExpectedSpineCount to be an explicit nil
func (o *PodsPutRequestPodValue) SetExpectedSpineCountNil() {
	o.ExpectedSpineCount.Set(nil)
}

// UnsetExpectedSpineCount ensures that no value is present for ExpectedSpineCount, not even an explicit nil
func (o *PodsPutRequestPodValue) UnsetExpectedSpineCount() {
	o.ExpectedSpineCount.Unset()
}

// GetFabric returns the Fabric field value if set, zero value otherwise.
func (o *PodsPutRequestPodValue) GetFabric() string {
	if o == nil || IsNil(o.Fabric) {
		var ret string
		return ret
	}
	return *o.Fabric
}

// GetFabricOk returns a tuple with the Fabric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodsPutRequestPodValue) GetFabricOk() (*string, bool) {
	if o == nil || IsNil(o.Fabric) {
		return nil, false
	}
	return o.Fabric, true
}

// HasFabric returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasFabric() bool {
	if o != nil && !IsNil(o.Fabric) {
		return true
	}

	return false
}

// SetFabric gets a reference to the given string and assigns it to the Fabric field.
func (o *PodsPutRequestPodValue) SetFabric(v string) {
	o.Fabric = &v
}

// GetFabricRefType returns the FabricRefType field value if set, zero value otherwise.
func (o *PodsPutRequestPodValue) GetFabricRefType() string {
	if o == nil || IsNil(o.FabricRefType) {
		var ret string
		return ret
	}
	return *o.FabricRefType
}

// GetFabricRefTypeOk returns a tuple with the FabricRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodsPutRequestPodValue) GetFabricRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FabricRefType) {
		return nil, false
	}
	return o.FabricRefType, true
}

// HasFabricRefType returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasFabricRefType() bool {
	if o != nil && !IsNil(o.FabricRefType) {
		return true
	}

	return false
}

// SetFabricRefType gets a reference to the given string and assigns it to the FabricRefType field.
func (o *PodsPutRequestPodValue) SetFabricRefType(v string) {
	o.FabricRefType = &v
}

// GetPosition returns the Position field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PodsPutRequestPodValue) GetPosition() float64 {
	if o == nil || IsNil(o.Position.Get()) {
		var ret float64
		return ret
	}
	return *o.Position.Get()
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PodsPutRequestPodValue) GetPositionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Position.Get(), o.Position.IsSet()
}

// HasPosition returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasPosition() bool {
	if o != nil && o.Position.IsSet() {
		return true
	}

	return false
}

// SetPosition gets a reference to the given NullableFloat64 and assigns it to the Position field.
func (o *PodsPutRequestPodValue) SetPosition(v float64) {
	o.Position.Set(&v)
}
// SetPositionNil sets the value for Position to be an explicit nil
func (o *PodsPutRequestPodValue) SetPositionNil() {
	o.Position.Set(nil)
}

// UnsetPosition ensures that no value is present for Position, not even an explicit nil
func (o *PodsPutRequestPodValue) UnsetPosition() {
	o.Position.Unset()
}

// GetObjectProperties returns the ObjectProperties field value if set, zero value otherwise.
func (o *PodsPutRequestPodValue) GetObjectProperties() AclsPutRequestIpFilterValueObjectProperties {
	if o == nil || IsNil(o.ObjectProperties) {
		var ret AclsPutRequestIpFilterValueObjectProperties
		return ret
	}
	return *o.ObjectProperties
}

// GetObjectPropertiesOk returns a tuple with the ObjectProperties field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PodsPutRequestPodValue) GetObjectPropertiesOk() (*AclsPutRequestIpFilterValueObjectProperties, bool) {
	if o == nil || IsNil(o.ObjectProperties) {
		return nil, false
	}
	return o.ObjectProperties, true
}

// HasObjectProperties returns a boolean if a field has been set.
func (o *PodsPutRequestPodValue) HasObjectProperties() bool {
	if o != nil && !IsNil(o.ObjectProperties) {
		return true
	}

	return false
}

// SetObjectProperties gets a reference to the given AclsPutRequestIpFilterValueObjectProperties and assigns it to the ObjectProperties field.
func (o *PodsPutRequestPodValue) SetObjectProperties(v AclsPutRequestIpFilterValueObjectProperties) {
	o.ObjectProperties = &v
}

func (o PodsPutRequestPodValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PodsPutRequestPodValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if o.ExpectedSpineCount.IsSet() {
		toSerialize["expected_spine_count"] = o.ExpectedSpineCount.Get()
	}
	if !IsNil(o.Fabric) {
		toSerialize["fabric"] = o.Fabric
	}
	if !IsNil(o.FabricRefType) {
		toSerialize["fabric_ref_type_"] = o.FabricRefType
	}
	if o.Position.IsSet() {
		toSerialize["position"] = o.Position.Get()
	}
	if !IsNil(o.ObjectProperties) {
		toSerialize["object_properties"] = o.ObjectProperties
	}
	return toSerialize, nil
}

type NullablePodsPutRequestPodValue struct {
	value *PodsPutRequestPodValue
	isSet bool
}

func (v NullablePodsPutRequestPodValue) Get() *PodsPutRequestPodValue {
	return v.value
}

func (v *NullablePodsPutRequestPodValue) Set(val *PodsPutRequestPodValue) {
	v.value = val
	v.isSet = true
}

func (v NullablePodsPutRequestPodValue) IsSet() bool {
	return v.isSet
}

func (v *NullablePodsPutRequestPodValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePodsPutRequestPodValue(val *PodsPutRequestPodValue) *NullablePodsPutRequestPodValue {
	return &NullablePodsPutRequestPodValue{value: val, isSet: true}
}

func (v NullablePodsPutRequestPodValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePodsPutRequestPodValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


