/*
Verity API

This application demonstrates the usage of Verity API. 

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ConfigPutRequestSwitchpointSwitchpointNameChildrenInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigPutRequestSwitchpointSwitchpointNameChildrenInner{}

// ConfigPutRequestSwitchpointSwitchpointNameChildrenInner struct for ConfigPutRequestSwitchpointSwitchpointNameChildrenInner
type ConfigPutRequestSwitchpointSwitchpointNameChildrenInner struct {
	// Switchpoint associated with the Child
	ChildNumEndpoint *string `json:"child_num_endpoint,omitempty"`
	// Object type for child_num_endpoint field
	ChildNumEndpointRefType *string `json:"child_num_endpoint_ref_type_,omitempty"`
	// Device associated with the Child
	ChildNumDevice *string `json:"child_num_device,omitempty"`
	// The index identifying the object. Zero if you want to add an object to the list.
	Index *int32 `json:"index,omitempty"`
}

// NewConfigPutRequestSwitchpointSwitchpointNameChildrenInner instantiates a new ConfigPutRequestSwitchpointSwitchpointNameChildrenInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigPutRequestSwitchpointSwitchpointNameChildrenInner() *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner {
	this := ConfigPutRequestSwitchpointSwitchpointNameChildrenInner{}
	var childNumEndpoint string = ""
	this.ChildNumEndpoint = &childNumEndpoint
	var childNumDevice string = ""
	this.ChildNumDevice = &childNumDevice
	return &this
}

// NewConfigPutRequestSwitchpointSwitchpointNameChildrenInnerWithDefaults instantiates a new ConfigPutRequestSwitchpointSwitchpointNameChildrenInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigPutRequestSwitchpointSwitchpointNameChildrenInnerWithDefaults() *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner {
	this := ConfigPutRequestSwitchpointSwitchpointNameChildrenInner{}
	var childNumEndpoint string = ""
	this.ChildNumEndpoint = &childNumEndpoint
	var childNumDevice string = ""
	this.ChildNumDevice = &childNumDevice
	return &this
}

// GetChildNumEndpoint returns the ChildNumEndpoint field value if set, zero value otherwise.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumEndpoint() string {
	if o == nil || IsNil(o.ChildNumEndpoint) {
		var ret string
		return ret
	}
	return *o.ChildNumEndpoint
}

// GetChildNumEndpointOk returns a tuple with the ChildNumEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.ChildNumEndpoint) {
		return nil, false
	}
	return o.ChildNumEndpoint, true
}

// HasChildNumEndpoint returns a boolean if a field has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) HasChildNumEndpoint() bool {
	if o != nil && !IsNil(o.ChildNumEndpoint) {
		return true
	}

	return false
}

// SetChildNumEndpoint gets a reference to the given string and assigns it to the ChildNumEndpoint field.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) SetChildNumEndpoint(v string) {
	o.ChildNumEndpoint = &v
}

// GetChildNumEndpointRefType returns the ChildNumEndpointRefType field value if set, zero value otherwise.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumEndpointRefType() string {
	if o == nil || IsNil(o.ChildNumEndpointRefType) {
		var ret string
		return ret
	}
	return *o.ChildNumEndpointRefType
}

// GetChildNumEndpointRefTypeOk returns a tuple with the ChildNumEndpointRefType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumEndpointRefTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ChildNumEndpointRefType) {
		return nil, false
	}
	return o.ChildNumEndpointRefType, true
}

// HasChildNumEndpointRefType returns a boolean if a field has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) HasChildNumEndpointRefType() bool {
	if o != nil && !IsNil(o.ChildNumEndpointRefType) {
		return true
	}

	return false
}

// SetChildNumEndpointRefType gets a reference to the given string and assigns it to the ChildNumEndpointRefType field.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) SetChildNumEndpointRefType(v string) {
	o.ChildNumEndpointRefType = &v
}

// GetChildNumDevice returns the ChildNumDevice field value if set, zero value otherwise.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumDevice() string {
	if o == nil || IsNil(o.ChildNumDevice) {
		var ret string
		return ret
	}
	return *o.ChildNumDevice
}

// GetChildNumDeviceOk returns a tuple with the ChildNumDevice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetChildNumDeviceOk() (*string, bool) {
	if o == nil || IsNil(o.ChildNumDevice) {
		return nil, false
	}
	return o.ChildNumDevice, true
}

// HasChildNumDevice returns a boolean if a field has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) HasChildNumDevice() bool {
	if o != nil && !IsNil(o.ChildNumDevice) {
		return true
	}

	return false
}

// SetChildNumDevice gets a reference to the given string and assigns it to the ChildNumDevice field.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) SetChildNumDevice(v string) {
	o.ChildNumDevice = &v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) SetIndex(v int32) {
	o.Index = &v
}

func (o ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChildNumEndpoint) {
		toSerialize["child_num_endpoint"] = o.ChildNumEndpoint
	}
	if !IsNil(o.ChildNumEndpointRefType) {
		toSerialize["child_num_endpoint_ref_type_"] = o.ChildNumEndpointRefType
	}
	if !IsNil(o.ChildNumDevice) {
		toSerialize["child_num_device"] = o.ChildNumDevice
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	return toSerialize, nil
}

type NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner struct {
	value *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner
	isSet bool
}

func (v NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) Get() *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner {
	return v.value
}

func (v *NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) Set(val *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner(val *ConfigPutRequestSwitchpointSwitchpointNameChildrenInner) *NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner {
	return &NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner{value: val, isSet: true}
}

func (v NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigPutRequestSwitchpointSwitchpointNameChildrenInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


